// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Price,
} from './';

/**
 * @export
 * @interface AccessoryPlan
 */
export interface AccessoryPlan {
    /**
     * @type {Price}
     * @memberof AccessoryPlan
     */
    billedAmount?: Price;
    /**
     * @type {number}
     * @memberof AccessoryPlan
     */
    billedMonths?: number;
    /**
     * @type {number}
     * @memberof AccessoryPlan
     */
    contractDuration?: number;
    /**
     * @type {string}
     * @memberof AccessoryPlan
     */
    contractEndDate?: string | null;
    /**
     * @type {string}
     * @memberof AccessoryPlan
     */
    contractStartDate?: string | null;
    /**
     * @type {Price}
     * @memberof AccessoryPlan
     */
    finalInstallment?: Price;
    /**
     * @type {Price}
     * @memberof AccessoryPlan
     */
    initialPayment?: Price;
    /**
     * @type {Price}
     * @memberof AccessoryPlan
     */
    monthlyInstallment?: Price;
    /**
     * @type {Price}
     * @memberof AccessoryPlan
     */
    outstandingAmount?: Price;
    /**
     * @type {number}
     * @memberof AccessoryPlan
     */
    outstandingFinalMonths?: number;
    /**
     * @type {number}
     * @memberof AccessoryPlan
     */
    outstandingMonths?: number;
    /**
     * @type {number}
     * @memberof AccessoryPlan
     */
    outstandingRecurringMonths?: number;
    /**
     * @type {number}
     * @memberof AccessoryPlan
     */
    payedInstallments?: number;
    /**
     * @type {Price}
     * @memberof AccessoryPlan
     */
    payedInstallmentsAmount?: Price;
    /**
     * @type {Price}
     * @memberof AccessoryPlan
     */
    totalPrice?: Price;
}
