// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AccessDescriptor,
    Technology,
} from './';

/**
 * @export
 * @interface Accesses
 */
export interface Accesses {
    /**
     * @type {AccessDescriptor}
     * @memberof Accesses
     */
    accessDescriptor?: AccessDescriptor;
    /**
     * @type {string}
     * @memberof Accesses
     */
    result?: string;
    /**
     * @type {string}
     * @memberof Accesses
     */
    code?: string;
    /**
     * @type {string}
     * @memberof Accesses
     */
    message?: string;
    /**
     * @type {Technology}
     * @memberof Accesses
     */
    technology?: Technology;
}
