// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AccessoryPlanStatusType,
    AccessoryPlanType,
} from './';

/**
 * @export
 * @interface AccessoryPlanInfoAllOf
 */
export interface AccessoryPlanInfoAllOf {
    /**
     * accessory plan id
     * @type {string}
     * @memberof AccessoryPlanInfoAllOf
     */
    accessoryPlanId: string;
    /**
     * @type {AccessoryPlanStatusType}
     * @memberof AccessoryPlanInfoAllOf
     */
    accessoryPlanStatus: AccessoryPlanStatusType;
    /**
     * @type {AccessoryPlanType}
     * @memberof AccessoryPlanInfoAllOf
     */
    accessoryPlanDetails?: AccessoryPlanType;
}
