// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AccessoryPlan,
} from './';

/**
 * @export
 * @interface AccessoryPlanDetails
 */
export interface AccessoryPlanDetails {
    /**
     * @type {string}
     * @memberof AccessoryPlanDetails
     */
    hardwareName?: string;
    /**
     * @type {AccessoryPlan}
     * @memberof AccessoryPlanDetails
     */
    sunAccessoryPlan?: AccessoryPlan;
}
