// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AccessDescriptor {
    BBC_SON_TDM_PPP_ADSL = 'BBCSonTDM_PPP_ADSL',
    BBC_SON_TDM_PPP_VDSL = 'BBCSonTDM_PPP_VDSL',
    BBC_SNAKED_PPP_ADSL = 'BBCSnaked_PPP_ADSL',
    BBC_SNAKED_PPP_VDSL = 'BBCSnaked_PPP_VDSL',
    BBC_SON_TDM_DHCP_ADSL = 'BBCSonTDM_DHCP_ADSL',
    BBC_SON_TDM_DHCP_VDSL = 'BBCSonTDM_DHCP_VDSL',
    BBC_SNAKED_DHCP_ADSL = 'BBCSnaked_DHCP_ADSL',
    BBC_SNAKED_DHCP_VDSL = 'BBCSnaked_DHCP_VDSL',
    XDS_LON_TAL_DHCP_ADSL2PLUS = 'XDSLonTAL_DHCP_ADSL2plus',
    XDS_LON_TAL_DHCP_ADSL2PLUS_M = 'XDSLonTAL_DHCP_ADSL2plusM',
    XDS_LON_TAL_DHCP_SHDSL = 'XDSLonTAL_DHCP_SHDSL',
    XDS_LON_TAL_DHCP_SHDS_LBIS = 'XDSLonTAL_DHCP_SHDSLbis',
    MSA_NON_TAL_BOTH_ADSL2PLUS = 'MSANonTAL_BOTH_ADSL2plus',
    L1_DHCP_FIBER = 'L1_DHCP_FIBER',
    L1_XGS_DHCP_FIBER = 'L1_XGS_DHCP_FIBER',
    L2_DHCP_FIBER = 'L2_DHCP_FIBER',
    L3_DHCP_FIBER_GB = 'L3_DHCP_FIBER_GB',
    L3_XGS_DHCP_FIBER = 'L3_XGS_DHCP_FIBER',
    MBB_DHCP = 'MBB_DHCP',
    ALETH = 'ALETH',
    ALETT = 'ALETT',
    CES = 'CES',
    CABLE_HFC = 'CABLE_HFC'
}

