// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AccessoryPlanInfo,
} from './';

/**
 * @export
 * @interface AccessoryPlanResponse
 */
export interface AccessoryPlanResponse {
    /**
     * serial of product
     * @type {string}
     * @memberof AccessoryPlanResponse
     */
    serial?: string;
    /**
     * @type {Array<AccessoryPlanInfo>}
     * @memberof AccessoryPlanResponse
     */
    accessoryPlans: Array<AccessoryPlanInfo>;
    /**
     * whether there are any pending orders on the site or subscription
     * @type {boolean}
     * @memberof AccessoryPlanResponse
     */
    pendingOrders: boolean;
}
