// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface AccountContact
 */
export interface AccountContact {
    /**
     * @type {string}
     * @memberof AccountContact
     */
    birthdate?: string;
    /**
     * @type {string}
     * @memberof AccountContact
     */
    email?: string;
    /**
     * @type {boolean}
     * @memberof AccountContact
     */
    emailConfirmed?: boolean;
    /**
     * @type {string}
     * @memberof AccountContact
     */
    firstName?: string;
    /**
     * @type {string}
     * @memberof AccountContact
     */
    languageCode?: string;
    /**
     * @type {string}
     * @memberof AccountContact
     */
    lastName?: string;
    /**
     * @type {string}
     * @memberof AccountContact
     */
    phone?: string;
    /**
     * @type {string}
     * @memberof AccountContact
     */
    salutation?: string;
}
