// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AccountContact,
    Address,
    FofDetails,
    Segment,
    Service,
    WeMobile,
} from './';

/**
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * @type {string}
     * @memberof Account
     */
    accountId?: string;
    /**
     * @type {AccountContact}
     * @memberof Account
     */
    contact?: AccountContact;
    /**
     * @type {Address}
     * @memberof Account
     */
    billingAddress?: Address;
    /**
     * @type {boolean}
     * @memberof Account
     */
    billingAddressSameAsPrimaryAddress?: boolean;
    /**
     * @type {Address}
     * @memberof Account
     */
    primaryAddress?: Address;
    /**
     * @type {WeMobile}
     * @memberof Account
     */
    weMobile?: WeMobile;
    /**
     * @type {FofDetails}
     * @memberof Account
     */
    friendOfFirm?: FofDetails;
    /**
     * @type {Array<Service>}
     * @memberof Account
     */
    services?: Array<Service>;
    /**
     * @type {Segment}
     * @memberof Account
     */
    segmentType?: Segment;
}
