// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CliInfo,
    Product,
    RatePlanType,
} from './';

/**
 * @export
 * @interface AccountRatePlan
 */
export interface AccountRatePlan {
    /**
     * @type {string}
     * @memberof AccountRatePlan
     */
    name?: string;
    /**
     * @type {string}
     * @memberof AccountRatePlan
     */
    status?: string;
    /**
     * @type {string}
     * @memberof AccountRatePlan
     */
    startDate?: string;
    /**
     * @type {string}
     * @memberof AccountRatePlan
     */
    endDate?: string;
    /**
     * @type {RatePlanType}
     * @memberof AccountRatePlan
     */
    type?: RatePlanType;
    /**
     * @type {Product}
     * @memberof AccountRatePlan
     */
    product?: Product;
    /**
     * @type {number}
     * @memberof AccountRatePlan
     */
    fee?: number;
    /**
     * @type {string}
     * @memberof AccountRatePlan
     */
    cliNumber?: string;
    /**
     * @type {Array<CliInfo>}
     * @memberof AccountRatePlan
     */
    cliNumbers?: Array<CliInfo>;
}
