// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ActionType {
    ADD = 'Add',
    DELETE = 'Delete',
    REPLACE_ADD = 'Replace/Add',
    REPLACE_ADD_MODIFY = 'Replace/AddModify',
    REPLACE_DELETE = 'Replace/Delete',
    REPLACE_DELETE_MODIFY = 'Replace/DeleteModify',
    ADD_SKIP = 'Add-Skip',
    DELETE_SKIP = 'Delete-Skip',
    REPLACE_ADD_SKIP = 'Replace/Add-Skip',
    REPLACE_DELETE_SKIP = 'Replace/Delete-Skip',
    CEASE = 'Cease',
    RELOCATION_ADD = 'Relocation/Add',
    RELOCATION_DELETE = 'Relocation/Delete',
    ADD_BILLING = 'AddBilling',
    REMOVE_BILLING = 'RemoveBilling',
    REFUND = 'Refund',
    RECONNECT = 'Reconnect',
    RECREATE = 'Recreate',
    CONVERSION = 'Conversion',
    MIGRATE = 'Migrate',
    ADD_CHILD = 'AddChild',
    MODIFY_INBOX = 'Modify Inbox',
    UPDATE = 'Update',
    MOBILE_REFERENCE = 'MobileReference',
    SKIP_ADD = 'SkipAdd',
    SKIP_DELETE = 'SkipDelete',
    SKIP_CEASE = 'SkipCease',
    SKIP_REPLACE_ADD = 'SkipReplaceAdd',
    SKIP_REPLACE_DELETE = 'SkipReplaceDelete',
    NONE = 'None'
}

