// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GlobalDiscountType,
    Language,
} from './';

/**
 * @export
 * @interface AddGlobalDiscountRequest
 */
export interface AddGlobalDiscountRequest {
    /**
     * @type {number}
     * @memberof AddGlobalDiscountRequest
     */
    discountAmount: number;
    /**
     * @type {GlobalDiscountType}
     * @memberof AddGlobalDiscountRequest
     */
    globalDiscountType: GlobalDiscountType;
    /**
     * @type {Language}
     * @memberof AddGlobalDiscountRequest
     */
    lang?: Language;
}
