// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Language,
} from './';

/**
 * @export
 * @interface AddProductWithVoucherPromoRequest
 */
export interface AddProductWithVoucherPromoRequest {
    /**
     * @type {number}
     * @memberof AddProductWithVoucherPromoRequest
     */
    bundleNo?: number;
    /**
     * @type {string}
     * @memberof AddProductWithVoucherPromoRequest
     */
    campaignId?: string;
    /**
     * @type {string}
     * @memberof AddProductWithVoucherPromoRequest
     */
    segmentCode?: string;
    /**
     * @type {string}
     * @memberof AddProductWithVoucherPromoRequest
     */
    serviceSerial?: string;
    /**
     * @type {string}
     * @memberof AddProductWithVoucherPromoRequest
     */
    siteId?: string;
    /**
     * @type {string}
     * @memberof AddProductWithVoucherPromoRequest
     */
    voucherCode?: string;
    /**
     * @type {Language}
     * @memberof AddProductWithVoucherPromoRequest
     */
    lang?: Language;
}
