// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * @type {string}
     * @memberof Address
     */
    additional?: string;
    /**
     * @type {string}
     * @memberof Address
     */
    countryIsoCode?: string;
    /**
     * @type {string}
     * @memberof Address
     */
    firstName?: string;
    /**
     * @type {string}
     * @memberof Address
     */
    lastName?: string;
    /**
     * @type {string}
     * @memberof Address
     */
    postalCode?: string;
    /**
     * @type {string}
     * @memberof Address
     */
    salutation?: string;
    /**
     * @type {string}
     * @memberof Address
     */
    streetName?: string;
    /**
     * @type {string}
     * @memberof Address
     */
    streetNumber?: string;
    /**
     * @type {string}
     * @memberof Address
     */
    town?: string;
}
