// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CartUserAction,
    Language,
    MobilePack,
    SegmentCode,
} from './';

/**
 * @export
 * @interface AddToCartRequest
 */
export interface AddToCartRequest {
    /**
     * @type {SegmentCode}
     * @memberof AddToCartRequest
     */
    segmentCode: SegmentCode;
    /**
     * @type {Array<CartUserAction>}
     * @memberof AddToCartRequest
     */
    userActions: Array<CartUserAction>;
    /**
     * @type {Language}
     * @memberof AddToCartRequest
     */
    lang?: Language;
    /**
     * Add items referred in the userActions in the same bundle.
     * @type {boolean}
     * @memberof AddToCartRequest
     */
    addToSameBundle?: boolean;
    /**
     * @type {MobilePack}
     * @memberof AddToCartRequest
     */
    custPreferredGroup?: MobilePack;
}
