// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface BillingTime
 */
export interface BillingTime {
    /**
     * @type {string}
     * @memberof BillingTime
     */
    code?: string;
    /**
     * @type {string}
     * @memberof BillingTime
     */
    description?: string;
    /**
     * @type {string}
     * @memberof BillingTime
     */
    name?: string;
    /**
     * @type {string}
     * @memberof BillingTime
     */
    nameInOrder?: string;
    /**
     * @type {number}
     * @memberof BillingTime
     */
    orderNumber?: number;
}
