// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Campaign,
    CodeListEntry,
    PriceBundleRule,
    SunOrderType,
} from './';

/**
 * @export
 * @interface BundleTemplate
 */
export interface BundleTemplate {
    /**
     * @type {string}
     * @memberof BundleTemplate
     */
    id?: string;
    /**
     * @type {Campaign}
     * @memberof BundleTemplate
     */
    campaignDetails?: Campaign;
    /**
     * @type {BundleTemplate}
     * @memberof BundleTemplate
     */
    parentTemplate?: BundleTemplate;
    /**
     * @type {Array<BundleTemplate>}
     * @memberof BundleTemplate
     */
    childBundleTemplates?: Array<BundleTemplate>;
    /**
     * @type {Array<PriceBundleRule>}
     * @memberof BundleTemplate
     */
    priceBundleRules?: Array<PriceBundleRule>;
    /**
     * @type {number}
     * @memberof BundleTemplate
     */
    maxItemsAllowed?: number;
    /**
     * @type {number}
     * @memberof BundleTemplate
     */
    minItemsRequired?: number;
    /**
     * @type {Array<string>}
     * @memberof BundleTemplate
     */
    processTypes?: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof BundleTemplate
     */
    segments?: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof BundleTemplate
     */
    sites?: Array<string>;
    /**
     * @type {SunOrderType}
     * @memberof BundleTemplate
     */
    sunOrderType?: SunOrderType;
    /**
     * @type {CodeListEntry}
     * @memberof BundleTemplate
     */
    segment?: CodeListEntry;
    /**
     * @type {string}
     * @memberof BundleTemplate
     */
    version?: string;
}
