// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Campaign
 */
export interface Campaign {
    /**
     * @type {string}
     * @memberof Campaign
     */
    campaignCategory?: string;
    /**
     * @type {string}
     * @memberof Campaign
     */
    code?: string;
    /**
     * @type {string}
     * @memberof Campaign
     */
    promoOrderType?: string;
    /**
     * @type {string}
     * @memberof Campaign
     */
    componentCode?: string;
    /**
     * @type {string}
     * @memberof Campaign
     */
    campaignDuration?: string;
    /**
     * @type {string}
     * @memberof Campaign
     */
    contractDuration?: string;
    /**
     * @type {string}
     * @memberof Campaign
     */
    campaignType?: string;
    /**
     * @type {string}
     * @memberof Campaign
     */
    description?: string;
    /**
     * @type {string}
     * @memberof Campaign
     */
    displayText?: string;
    /**
     * @type {string}
     * @memberof Campaign
     */
    startDate?: string | null;
    /**
     * @type {string}
     * @memberof Campaign
     */
    endDate?: string | null;
}
