// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum CampaignType {
    SMS = 'SMS',
    FLEXIBLE_BENEFIT = 'FLEXIBLE_BENEFIT',
    VOUCHER = 'VOUCHER',
    BINDING_PROMO = 'BINDING_PROMO',
    BINDING_PROMO_WITH_GIFT = 'BINDING_PROMO_WITH_GIFT',
    BINDING_PROMO_DP_SUBSIDY = 'BINDING_PROMO_DP_SUBSIDY',
    VOUCHER_GENERATING_PROMO = 'VOUCHER_GENERATING_PROMO'
}

