// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CaptureOrderErrorType,
    KeyValuePairType,
    LineItemType,
} from './';

/**
 * @export
 * @interface CaptureBaseResponseType
 */
export interface CaptureBaseResponseType {
    /**
     * @type {CaptureOrderErrorType}
     * @memberof CaptureBaseResponseType
     */
    errorCode?: CaptureOrderErrorType;
    /**
     * index of order
     * @type {string}
     * @memberof CaptureBaseResponseType
     */
    orderIndex?: string;
    /**
     * product name
     * @type {string}
     * @memberof CaptureBaseResponseType
     */
    productName?: string;
    /**
     * The product identifier (msisdn or U-number). Can be empty for a New order.
     * @type {string}
     * @memberof CaptureBaseResponseType
     */
    serial?: string;
    /**
     * order quation id
     * @type {string}
     * @memberof CaptureBaseResponseType
     */
    quotationId?: string;
    /**
     * Is this product a main subscription in We Mobile Set.
     * @type {boolean}
     * @memberof CaptureBaseResponseType
     */
    isMobilePackFirstSubscription?: boolean;
    /**
     * When promotion name is provided in the request but by some reason it is not eligible, here will be description of ineligibility reason.
     * @type {string}
     * @memberof CaptureBaseResponseType
     */
    promoIneligibilityReason?: string;
    /**
     * @type {Array<KeyValuePairType>}
     * @memberof CaptureBaseResponseType
     */
    orderAttributes?: Array<KeyValuePairType>;
    /**
     * @type {Array<LineItemType>}
     * @memberof CaptureBaseResponseType
     */
    lineItems?: Array<LineItemType>;
}
