// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BundleTemplate,
    CartCustomer,
    GlobalDiscount,
    OrderEntry,
    Price,
    PromotionResult,
} from './';

/**
 * @export
 * @interface Cart
 */
export interface Cart {
    /**
     * @type {Array<PromotionResult>}
     * @memberof Cart
     */
    appliedProductPromotions?: Array<PromotionResult>;
    /**
     * @type {BundleTemplate}
     * @memberof Cart
     */
    cartPackage?: BundleTemplate;
    /**
     * @type {CartCustomer}
     * @memberof Cart
     */
    customer?: CartCustomer;
    /**
     * @type {Array<OrderEntry>}
     * @memberof Cart
     */
    entries?: Array<OrderEntry>;
    /**
     * @type {Array<GlobalDiscount>}
     * @memberof Cart
     */
    globalDiscounts?: Array<GlobalDiscount>;
    /**
     * @type {string}
     * @memberof Cart
     */
    guid?: string;
    /**
     * @type {Price}
     * @memberof Cart
     */
    totalPrice?: Price;
    /**
     * @type {string}
     * @memberof Cart
     */
    pipOrderId?: string;
    /**
     * @type {Array<Price>}
     * @memberof Cart
     */
    totalRecurringCharges?: Array<Price>;
}
