// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    FirmCategory,
    ProcessType,
    SpecialFields,
} from './';

/**
 * @export
 * @interface CartUserAction
 */
export interface CartUserAction {
    /**
     * @type {string}
     * @memberof CartUserAction
     */
    action: string;
    /**
     * @type {number}
     * @memberof CartUserAction
     */
    bundleNo?: number;
    /**
     * @type {string}
     * @memberof CartUserAction
     */
    componentCode: string;
    /**
     * @type {string}
     * @memberof CartUserAction
     */
    productCode: string;
    /**
     * @type {string}
     * @memberof CartUserAction
     */
    serviceSerial?: string;
    /**
     * @type {number}
     * @memberof CartUserAction
     */
    hardwarePlanTerm?: number;
    /**
     * @type {number}
     * @memberof CartUserAction
     */
    hardwareUpfront?: number;
    /**
     * @type {number}
     * @memberof CartUserAction
     */
    quantity?: number;
    /**
     * Terminate existing Device Plan by paying the remaining installments amount.
     * @type {boolean}
     * @memberof CartUserAction
     */
    hasPayOff?: boolean;
    /**
     * @type {ProcessType}
     * @memberof CartUserAction
     */
    processType?: ProcessType;
    /**
     * @type {FirmCategory}
     * @memberof CartUserAction
     */
    firmCategory?: FirmCategory;
    /**
     * @type {Array<SpecialFields>}
     * @memberof CartUserAction
     */
    specialFields?: Array<SpecialFields>;
}
