// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CartModifications,
    PromotionDiscount,
} from './';

/**
 * @export
 * @interface CartModificationList
 */
export interface CartModificationList {
    /**
     * @type {Array<CartModifications>}
     * @memberof CartModificationList
     */
    cartModifications?: Array<CartModifications>;
    /**
     * @type {PromotionDiscount}
     * @memberof CartModificationList
     */
    promotionDetails?: PromotionDiscount;
}
