// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BundleTemplate,
    OrderEntry,
} from './';

/**
 * @export
 * @interface CartModifications
 */
export interface CartModifications {
    /**
     * @type {string}
     * @memberof CartModifications
     */
    cartCode?: string;
    /**
     * @type {BundleTemplate}
     * @memberof CartModifications
     */
    cartPackage?: BundleTemplate;
    /**
     * @type {boolean}
     * @memberof CartModifications
     */
    deliveryModeChanged?: boolean;
    /**
     * @type {OrderEntry}
     * @memberof CartModifications
     */
    entry?: OrderEntry;
    /**
     * @type {string}
     * @memberof CartModifications
     */
    guid?: string;
    /**
     * @type {number}
     * @memberof CartModifications
     */
    quantity?: number;
    /**
     * @type {number}
     * @memberof CartModifications
     */
    quantityAdded?: number;
}
