// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CliInfoType,
} from './';

/**
 * @export
 * @interface CliInfo
 */
export interface CliInfo {
    /**
     * @type {string}
     * @memberof CliInfo
     */
    number?: string;
    /**
     * @type {CliInfoType}
     * @memberof CliInfo
     */
    type?: CliInfoType;
}
