// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CliPortabilityStatus,
} from './';

/**
 * @export
 * @interface CliPortabilityCheckResponse
 */
export interface CliPortabilityCheckResponse {
    /**
     * @type {boolean}
     * @memberof CliPortabilityCheckResponse
     */
    eligible?: boolean;
    /**
     * @type {string}
     * @memberof CliPortabilityCheckResponse
     */
    tspId?: string;
    /**
     * @type {string}
     * @memberof CliPortabilityCheckResponse
     */
    tspName?: string;
    /**
     * @type {string}
     * @memberof CliPortabilityCheckResponse
     */
    resellerId?: string;
    /**
     * @type {string}
     * @memberof CliPortabilityCheckResponse
     */
    cli: string;
    /**
     * @type {CliPortabilityStatus}
     * @memberof CliPortabilityCheckResponse
     */
    eligibilityStatus: CliPortabilityStatus;
}
