// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum CliPortabilityStatus {
    OK = 'OK',
    DUPLICATE = 'DUPLICATE',
    CLI_UNKNOWN = 'CLI_UNKNOWN',
    DONOR_MISMATCH = 'DONOR_MISMATCH',
    RDB_INPORT_NOK = 'RDB_INPORT_NOK',
    ISDN_MAIN_NUMBER_MISMATCH = 'ISDN_MAIN_NUMBER_MISMATCH',
    ISDN_VALIDATION_NOK = 'ISDN_VALIDATION_NOK'
}

