// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Color
 */
export interface Color {
    /**
     * @type {string}
     * @memberof Color
     */
    code?: string;
    /**
     * @type {string}
     * @memberof Color
     */
    value?: string;
    /**
     * @type {string}
     * @memberof Color
     */
    colorHexValue?: string;
}
