// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CompanyRegistrationStatus,
    UIDStatus,
} from './';

/**
 * @export
 * @interface CompanyDetailsInput
 */
export interface CompanyDetailsInput {
    /**
     * Company UID number for Business Customers
     * @type {string}
     * @memberof CompanyDetailsInput
     */
    companyUid: string;
    /**
     * @type {UIDStatus}
     * @memberof CompanyDetailsInput
     */
    uidStatus?: UIDStatus;
    /**
     * Legal Entity Number
     * @type {string}
     * @memberof CompanyDetailsInput
     */
    legalEntity?: string;
    /**
     * Legal Entity based on Language
     * @type {string}
     * @memberof CompanyDetailsInput
     */
    legalEntityName?: string;
    /**
     * Abbrevation based on Language
     * @type {string}
     * @memberof CompanyDetailsInput
     */
    abbreviation?: string;
    /**
     * Company UID registration
     * @type {string}
     * @memberof CompanyDetailsInput
     */
    companyUidReg?: string;
    /**
     * formation date
     * @type {string}
     * @memberof CompanyDetailsInput
     */
    foundationDate?: string | null;
    /**
     * @type {CompanyRegistrationStatus}
     * @memberof CompanyDetailsInput
     */
    registrationStatus?: CompanyRegistrationStatus;
    /**
     * Legal Entity white listed or not
     * @type {boolean}
     * @memberof CompanyDetailsInput
     */
    isLegalEntityWhitelist?: boolean;
}
