// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CompanyRegistrationStatus,
} from './';

/**
 * @export
 * @interface CompanyInfo
 */
export interface CompanyInfo {
    /**
     * UID of company
     * @type {string}
     * @memberof CompanyInfo
     */
    uid?: string;
    /**
     * Company UID registration
     * @type {string}
     * @memberof CompanyInfo
     */
    companyUidReg?: string;
    /**
     * Company legal name
     * @type {string}
     * @memberof CompanyInfo
     */
    legalName?: string;
    /**
     * Legal Entity no
     * @type {string}
     * @memberof CompanyInfo
     */
    legalEntity?: string;
    /**
     * Legal Entity name in English
     * @type {string}
     * @memberof CompanyInfo
     */
    legalEntityNameEN?: string;
    /**
     * Legal Entity name in Dutch
     * @type {string}
     * @memberof CompanyInfo
     */
    legalEntityNameDE?: string;
    /**
     * Legal Entity name in French
     * @type {string}
     * @memberof CompanyInfo
     */
    legalEntityNameFR?: string;
    /**
     * Legal Entity name in Italian
     * @type {string}
     * @memberof CompanyInfo
     */
    legalEntityNameIT?: string;
    /**
     * @type {string}
     * @memberof CompanyInfo
     */
    abbreviationEN?: string;
    /**
     * @type {string}
     * @memberof CompanyInfo
     */
    abbreviationDE?: string;
    /**
     * @type {string}
     * @memberof CompanyInfo
     */
    abbreviationFR?: string;
    /**
     * @type {string}
     * @memberof CompanyInfo
     */
    abbreviationIT?: string;
    /**
     * Legal Entity white listed or not
     * @type {boolean}
     * @memberof CompanyInfo
     */
    isLegalEntityWhitelist?: boolean;
    /**
     * formation date
     * @type {string}
     * @memberof CompanyInfo
     */
    foundationDate?: string | null;
    /**
     * expiration date
     * @type {string}
     * @memberof CompanyInfo
     */
    expirationDate?: string | null;
    /**
     * @type {CompanyRegistrationStatus}
     * @memberof CompanyInfo
     */
    registrationStatus?: CompanyRegistrationStatus;
}
