// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BusinessLegalAddressee,
    CompanyInfo,
} from './';

/**
 * @export
 * @interface CompanyResponse
 */
export interface CompanyResponse {
    /**
     * @type {BusinessLegalAddressee}
     * @memberof CompanyResponse
     */
    businessLegalAddressee?: BusinessLegalAddressee;
    /**
     * @type {CompanyInfo}
     * @memberof CompanyResponse
     */
    companyInfo?: CompanyInfo;
}
