// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Contract
 */
export interface Contract {
    /**
     * @type {string}
     * @memberof Contract
     */
    startDate?: string;
    /**
     * @type {string}
     * @memberof Contract
     */
    endDate?: string;
    /**
     * @type {number}
     * @memberof Contract
     */
    duration?: number;
}
