// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AgentReference,
    AppointmentReference,
    LineCheckAddress,
    NotificationReference,
    OfferCustomer,
    OfferType,
    PreferredCommChannel,
    QualificationType,
    Shop,
    Technology,
} from './';

/**
 * @export
 * @interface CreateOfferWithPrintRequest
 */
export interface CreateOfferWithPrintRequest {
    /**
     * @type {string}
     * @memberof CreateOfferWithPrintRequest
     */
    cartId: string;
    /**
     * @type {PreferredCommChannel}
     * @memberof CreateOfferWithPrintRequest
     */
    communicationChannel?: PreferredCommChannel;
    /**
     * @type {LineCheckAddress}
     * @memberof CreateOfferWithPrintRequest
     */
    address?: LineCheckAddress;
    /**
     * @type {string}
     * @memberof CreateOfferWithPrintRequest
     */
    lri?: string;
    /**
     * @type {QualificationType}
     * @memberof CreateOfferWithPrintRequest
     */
    qualification?: QualificationType;
    /**
     * @type {OfferCustomer}
     * @memberof CreateOfferWithPrintRequest
     */
    customer?: OfferCustomer;
    /**
     * @type {boolean}
     * @memberof CreateOfferWithPrintRequest
     */
    isDiffBillingAddress?: boolean;
    /**
     * @type {Technology}
     * @memberof CreateOfferWithPrintRequest
     */
    technology?: Technology;
    /**
     * @type {string}
     * @memberof CreateOfferWithPrintRequest
     */
    agentNotes?: string;
    /**
     * @type {string}
     * @memberof CreateOfferWithPrintRequest
     */
    customerNotes?: string;
    /**
     * @type {AppointmentReference}
     * @memberof CreateOfferWithPrintRequest
     */
    appointment?: AppointmentReference;
    /**
     * @type {AgentReference}
     * @memberof CreateOfferWithPrintRequest
     */
    agent?: AgentReference;
    /**
     * @type {Shop}
     * @memberof CreateOfferWithPrintRequest
     */
    shop?: Shop;
    /**
     * @type {OfferType}
     * @memberof CreateOfferWithPrintRequest
     */
    offerType: OfferType;
    /**
     * @type {NotificationReference}
     * @memberof CreateOfferWithPrintRequest
     */
    notification?: NotificationReference;
}
