// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    OfferPrintStatusType,
} from './';

/**
 * @export
 * @interface CreateOfferWithPrintResponse
 */
export interface CreateOfferWithPrintResponse {
    /**
     * @type {string}
     * @memberof CreateOfferWithPrintResponse
     */
    offerId: string;
    /**
     * @type {string}
     * @memberof CreateOfferWithPrintResponse
     */
    externalOfferId?: string;
    /**
     * @type {string}
     * @memberof CreateOfferWithPrintResponse
     */
    description?: string;
    /**
     * @type {OfferPrintStatusType}
     * @memberof CreateOfferWithPrintResponse
     */
    status: OfferPrintStatusType;
    /**
     * @type {string}
     * @memberof CreateOfferWithPrintResponse
     */
    documentLookUpId?: string;
}
