// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    LineCheckAddress,
    OfferCustomer,
    PreferredCommChannel,
    QualificationType,
    Technology,
} from './';

/**
 * @export
 * @interface CreateOfferRequest
 */
export interface CreateOfferRequest {
    /**
     * @type {string}
     * @memberof CreateOfferRequest
     */
    cartId: string;
    /**
     * @type {PreferredCommChannel}
     * @memberof CreateOfferRequest
     */
    communicationChannel?: PreferredCommChannel;
    /**
     * @type {LineCheckAddress}
     * @memberof CreateOfferRequest
     */
    address?: LineCheckAddress;
    /**
     * @type {string}
     * @memberof CreateOfferRequest
     */
    lri?: string;
    /**
     * @type {QualificationType}
     * @memberof CreateOfferRequest
     */
    qualification?: QualificationType;
    /**
     * @type {OfferCustomer}
     * @memberof CreateOfferRequest
     */
    customer?: OfferCustomer;
    /**
     * @type {boolean}
     * @memberof CreateOfferRequest
     */
    isDiffBillingAddress?: boolean;
    /**
     * @type {Technology}
     * @memberof CreateOfferRequest
     */
    technology?: Technology;
    /**
     * @type {string}
     * @memberof CreateOfferRequest
     */
    agentNotes?: string;
    /**
     * @type {string}
     * @memberof CreateOfferRequest
     */
    customerNotes?: string;
}
