// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IdentityType,
    Segment,
} from './';

/**
 * @export
 * @interface CreditCheckCustomerInfo
 */
export interface CreditCheckCustomerInfo {
    /**
     * @type {string}
     * @memberof CreditCheckCustomerInfo
     */
    firstName: string;
    /**
     * @type {string}
     * @memberof CreditCheckCustomerInfo
     */
    lastName: string;
    /**
     * @type {Segment}
     * @memberof CreditCheckCustomerInfo
     */
    segment: Segment;
    /**
     * @type {string}
     * @memberof CreditCheckCustomerInfo
     */
    birthDate: string;
    /**
     * @type {IdentityType}
     * @memberof CreditCheckCustomerInfo
     */
    identityType: IdentityType;
    /**
     * @type {string}
     * @memberof CreditCheckCustomerInfo
     */
    street: string;
    /**
     * @type {string}
     * @memberof CreditCheckCustomerInfo
     */
    houseNr: string;
    /**
     * @type {string}
     * @memberof CreditCheckCustomerInfo
     */
    city: string;
    /**
     * @type {string}
     * @memberof CreditCheckCustomerInfo
     */
    zipCode: string;
}
