// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CreditCheckCustomerInfo,
    RequestType,
    ServiceSubType,
    ServiceType,
} from './';

/**
 * @export
 * @interface CreditCheckEligibilityRequest
 */
export interface CreditCheckEligibilityRequest {
    /**
     * @type {RequestType}
     * @memberof CreditCheckEligibilityRequest
     */
    requestType: RequestType;
    /**
     * @type {Array<ServiceType>}
     * @memberof CreditCheckEligibilityRequest
     */
    serviceTypes: Array<ServiceType>;
    /**
     * @type {ServiceSubType}
     * @memberof CreditCheckEligibilityRequest
     */
    serviceSubType?: ServiceSubType;
    /**
     * @type {CreditCheckCustomerInfo}
     * @memberof CreditCheckEligibilityRequest
     */
    customerInfo?: CreditCheckCustomerInfo;
}
