// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DevicePlanStatus,
    DevicePlanType,
} from './';

/**
 * @export
 * @interface DevicePlanInfo
 */
export interface DevicePlanInfo {
    /**
     * @type {DevicePlanType}
     * @memberof DevicePlanInfo
     */
    devicePlanDetails?: DevicePlanType;
    /**
     * device plan id
     * @type {string}
     * @memberof DevicePlanInfo
     */
    devicePlanId: string;
    /**
     * @type {DevicePlanStatus}
     * @memberof DevicePlanInfo
     */
    devicePlanStatus: DevicePlanStatus;
    /**
     * Earlieast renewal date of device plan
     * @type {string}
     * @memberof DevicePlanInfo
     */
    earliestRenewalDate?: string | null;
    /**
     * Earlieast upgrade date of device plan
     * @type {string}
     * @memberof DevicePlanInfo
     */
    earliestUpgradeDate?: string | null;
    /**
     * end date of device plan
     * @type {string}
     * @memberof DevicePlanInfo
     */
    endDate: string;
    /**
     * paid no of installments
     * @type {number}
     * @memberof DevicePlanInfo
     */
    paidInstalments: number;
    /**
     * paid amount for each installment
     * @type {number}
     * @memberof DevicePlanInfo
     */
    paidInstalmentsAmount: number;
    /**
     * ramining no of installments
     * @type {number}
     * @memberof DevicePlanInfo
     */
    remainingInstalments: number;
    /**
     * ramining no of installment amount
     * @type {number}
     * @memberof DevicePlanInfo
     */
    remainingInstalmentsAmount: number;
    /**
     * start date of device plan
     * @type {string}
     * @memberof DevicePlanInfo
     */
    startDate: string;
    /**
     * Termination date of device plan
     * @type {string}
     * @memberof DevicePlanInfo
     */
    terminationDate?: string | null;
    /**
     * Upgrage eligible or not
     * @type {boolean}
     * @memberof DevicePlanInfo
     */
    upgradeEligible?: boolean;
}
