// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AccessoryPlanDetails,
    DevicePlan,
} from './';

/**
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * @type {Array<AccessoryPlanDetails>}
     * @memberof Device
     */
    accessoryPlanDetailsDataList?: Array<AccessoryPlanDetails>;
    /**
     * @type {Array<DevicePlan>}
     * @memberof Device
     */
    deviceDetails?: Array<DevicePlan>;
    /**
     * @type {string}
     * @memberof Device
     */
    deviceImei?: string;
    /**
     * @type {string}
     * @memberof Device
     */
    deviceName?: string;
    /**
     * @type {DevicePlan}
     * @memberof Device
     */
    devicePlan?: DevicePlan;
    /**
     * @type {string}
     * @memberof Device
     */
    deviceSoftware?: string;
    /**
     * @type {string}
     * @memberof Device
     */
    deviceSpecUrl?: string;
    /**
     * @type {string}
     * @memberof Device
     */
    deviceVendor?: string;
    /**
     * @type {string}
     * @memberof Device
     */
    deviceVendorUrl?: string;
    /**
     * @type {string}
     * @memberof Device
     */
    deviceWebUrl?: string;
    /**
     * @type {boolean}
     * @memberof Device
     */
    newDPEligible?: boolean;
    /**
     * @type {Array<DevicePlan>}
     * @memberof Device
     */
    payOffChoices?: Array<DevicePlan>;
    /**
     * @type {boolean}
     * @memberof Device
     */
    showReservationStatusButton?: boolean | null;
    /**
     * @type {string}
     * @memberof Device
     */
    serial?: string;
}
