// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DevicePlanInfo,
} from './';

/**
 * @export
 * @interface DevicePlanResponse
 */
export interface DevicePlanResponse {
    /**
     * @type {Array<DevicePlanInfo>}
     * @memberof DevicePlanResponse
     */
    devicePlans: Array<DevicePlanInfo>;
    /**
     * whether there are any pending orders on the site or subscription
     * @type {boolean}
     * @memberof DevicePlanResponse
     */
    pendingOrders: boolean;
    /**
     * @type {string}
     * @memberof DevicePlanResponse
     */
    serial: string;
}
