// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Discount
 */
export interface Discount {
    /**
     * @type {boolean}
     * @memberof Discount
     */
    absolute?: boolean;
    /**
     * @type {boolean}
     * @memberof Discount
     */
    isPromotionDependent?: boolean;
    /**
     * @type {string}
     * @memberof Discount
     */
    name?: string;
    /**
     * @type {number}
     * @memberof Discount
     */
    numberOfMonths?: number;
    /**
     * @type {number}
     * @memberof Discount
     */
    value?: number;
}
