// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface DiscountSourceType
 */
export interface DiscountSourceType {
    /**
     * binding promo end date
     * @type {string}
     * @memberof DiscountSourceType
     */
    bindingPromoEndDate?: string | null;
    /**
     * source type other than binding promo
     * @type {string}
     * @memberof DiscountSourceType
     */
    bindingPromoName?: string;
    /**
     * source type other than binding promo
     * @type {string}
     * @memberof DiscountSourceType
     */
    other?: string;
}
