// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ElectricianPackageType {
    NONE = 'NONE',
    HOMEINSTALL_ONLY = 'HOMEINSTALL_ONLY',
    UPK_AND_HOMEINSTALL = 'UPK_AND_HOMEINSTALL',
    UPK_ONLY = 'UPK_ONLY',
    BASIC_INSTALL = 'BASIC_INSTALL',
    UPK_AND_BASICINSTALL = 'UPK_AND_BASICINSTALL',
    FIBER_HOMEINSTALL_ONLY = 'FIBER_HOMEINSTALL_ONLY',
    CUSTOMER_OWN_ELECTRICIAN = 'CUSTOMER_OWN_ELECTRICIAN',
    T3_ONLY = 'T3_ONLY',
    T3_AND_HOMEINSTALL = 'T3_AND_HOMEINSTALL',
    T3_AND_BASICINSTALL = 'T3_AND_BASICINSTALL',
    HOME_INSTALLATION_ONLY = 'HOME_INSTALLATION_ONLY',
    UPK_HOME_INSTALLATION = 'UPK_HOME_INSTALLATION',
    BASIC_INSTALLATION = 'BASIC_INSTALLATION',
    UPK_BASIC_INSTALLATION = 'UPK_BASIC_INSTALLATION',
    NO_ELECTRICIAN = 'NO_ELECTRICIAN',
    PARTNER_NETWORK_ELECTRICIAN = 'PARTNER_NETWORK_ELECTRICIAN'
}

