// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Language,
    LineCheckAddress,
    Segment,
    Technology,
} from './';

/**
 * @export
 * @interface ElectricianEligibilityRequest
 */
export interface ElectricianEligibilityRequest {
    /**
     * Required when Modification or Migration
     * @type {string}
     * @memberof ElectricianEligibilityRequest
     */
    serial?: string;
    /**
     * @type {LineCheckAddress}
     * @memberof ElectricianEligibilityRequest
     */
    address: LineCheckAddress;
    /**
     * @type {Segment}
     * @memberof ElectricianEligibilityRequest
     */
    segment: Segment;
    /**
     * @type {string}
     * @memberof ElectricianEligibilityRequest
     */
    parentProduct: string;
    /**
     * @type {Array<string>}
     * @memberof ElectricianEligibilityRequest
     */
    eligibleProducts: Array<string>;
    /**
     * @type {Technology}
     * @memberof ElectricianEligibilityRequest
     */
    technology?: Technology;
    /**
     * @type {Language}
     * @memberof ElectricianEligibilityRequest
     */
    lang?: Language;
}
