// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface EligibilitySummaryInfo
 */
export interface EligibilitySummaryInfo {
    /**
     * @type {number}
     * @memberof EligibilitySummaryInfo
     */
    usedProduct: number;
    /**
     * @type {number}
     * @memberof EligibilitySummaryInfo
     */
    maxProduct: number;
    /**
     * @type {number}
     * @memberof EligibilitySummaryInfo
     */
    remainingProduct: number;
    /**
     * @type {string}
     * @memberof EligibilitySummaryInfo
     */
    inEligibilityReason?: string;
    /**
     * @type {number}
     * @memberof EligibilitySummaryInfo
     */
    deposit?: number;
    /**
     * @type {number}
     * @memberof EligibilitySummaryInfo
     */
    maxAllowedCreditPerProduct?: number;
    /**
     * @type {string}
     * @memberof EligibilitySummaryInfo
     */
    eligibilityRiskBand?: string;
    /**
     * @type {boolean}
     * @memberof EligibilitySummaryInfo
     */
    prePaymentRequired?: boolean;
    /**
     * @type {string}
     * @memberof EligibilitySummaryInfo
     */
    hardwarePrePayment?: string;
}
