// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Access,
    RatePlan,
} from './';

/**
 * @export
 * @interface EligibleBundle
 */
export interface EligibleBundle {
    /**
     * @type {Array<RatePlan>}
     * @memberof EligibleBundle
     */
    products: Array<RatePlan>;
    /**
     * @type {Array<Access>}
     * @memberof EligibleBundle
     */
    access: Array<Access>;
}
