// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface EligibleRateplanType
 */
export interface EligibleRateplanType {
    /**
     * product name
     * @type {string}
     * @memberof EligibleRateplanType
     */
    productName?: string;
    /**
     * discount on product
     * @type {number}
     * @memberof EligibleRateplanType
     */
    discount?: number;
}
