// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    SearchState,
} from './';

/**
 * @export
 * @interface FacetValue
 */
export interface FacetValue {
    /**
     * @type {string}
     * @memberof FacetValue
     */
    code?: string;
    /**
     * @type {number}
     * @memberof FacetValue
     */
    count?: number;
    /**
     * @type {string}
     * @memberof FacetValue
     */
    name?: string;
    /**
     * @type {SearchState}
     * @memberof FacetValue
     */
    query?: SearchState;
    /**
     * @type {boolean}
     * @memberof FacetValue
     */
    selected?: boolean;
}
