// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    FacetValue,
} from './';

/**
 * @export
 * @interface Facet
 */
export interface Facet {
    /**
     * @type {boolean}
     * @memberof Facet
     */
    category?: boolean;
    /**
     * @type {string}
     * @memberof Facet
     */
    code?: string;
    /**
     * @type {boolean}
     * @memberof Facet
     */
    multiSelect?: boolean;
    /**
     * @type {string}
     * @memberof Facet
     */
    name?: string;
    /**
     * @type {number}
     * @memberof Facet
     */
    priority?: number;
    /**
     * @type {Array<FacetValue>}
     * @memberof Facet
     */
    topValues?: Array<FacetValue>;
    /**
     * @type {Array<FacetValue>}
     * @memberof Facet
     */
    values?: Array<FacetValue>;
    /**
     * @type {boolean}
     * @memberof Facet
     */
    visible?: boolean;
}
