// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface FirmDetailType
 */
export interface FirmDetailType {
    /**
     * FOF name
     * @type {string}
     * @memberof FirmDetailType
     */
    name: string;
    /**
     * FOF identifier for a customer
     * @type {string}
     * @memberof FirmDetailType
     */
    type: string;
    /**
     * category Family
     * @type {string}
     * @memberof FirmDetailType
     */
    family?: string;
    /**
     * @type {number}
     * @memberof FirmDetailType
     */
    maxAllowedSubscriptions?: number;
    /**
     * Discount in percentage
     * @type {number}
     * @memberof FirmDetailType
     */
    discountPerc?: number;
    /**
     * Minimum duration of discount on site category
     * @type {number}
     * @memberof FirmDetailType
     */
    minimumDuration?: number;
}
