// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CategoryDistinctionType,
} from './';

/**
 * @export
 * @interface FofDetails
 */
export interface FofDetails {
    /**
     * FOF name
     * @type {string}
     * @memberof FofDetails
     */
    name: string;
    /**
     * FOF identifier for a customer
     * @type {string}
     * @memberof FofDetails
     */
    type: string;
    /**
     * category Family
     * @type {string}
     * @memberof FofDetails
     */
    family?: string;
    /**
     * @type {number}
     * @memberof FofDetails
     */
    maxAllowedFoFDiscounts?: number;
    /**
     * Discount in percentage
     * @type {number}
     * @memberof FofDetails
     */
    discountPerc?: number;
    /**
     * Minimum duration of discount on site category
     * @type {number}
     * @memberof FofDetails
     */
    minimumDuration?: number;
    /**
     * @type {string}
     * @memberof FofDetails
     */
    startDate?: string;
    /**
     * @type {string}
     * @memberof FofDetails
     */
    endDate?: string;
    /**
     * @type {CategoryDistinctionType}
     * @memberof FofDetails
     */
    categoryDistinction?: CategoryDistinctionType;
}
