// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface GetClisResponse
 */
export interface GetClisResponse {
    /**
     * @type {Array<string>}
     * @memberof GetClisResponse
     */
    standard?: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof GetClisResponse
     */
    golden?: Array<string>;
}
