// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface GetDevicePlanEligibilityResponse
 */
export interface GetDevicePlanEligibilityResponse {
    /**
     * @type {string}
     * @memberof GetDevicePlanEligibilityResponse
     */
    serial: string;
    /**
     * device plan count
     * @type {number}
     * @memberof GetDevicePlanEligibilityResponse
     */
    devicePlanCount: number;
    /**
     * max device plan count
     * @type {number}
     * @memberof GetDevicePlanEligibilityResponse
     */
    maxDevicePlanCount: number;
    /**
     * new device plan allowed or not
     * @type {boolean}
     * @memberof GetDevicePlanEligibilityResponse
     */
    newDevicePlanAllowed: boolean;
}
