// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CaptureBaseResponseType,
} from './';

/**
 * @export
 * @interface GetEligiblePromotionsResponse
 */
export interface GetEligiblePromotionsResponse {
    /**
     * @type {Array<CaptureBaseResponseType>}
     * @memberof GetEligiblePromotionsResponse
     */
    products?: Array<CaptureBaseResponseType>;
}
