// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CampaignType,
    Language,
    Segment,
} from './';

/**
 * @export
 * @interface GetEligiblePromotionsRequest
 */
export interface GetEligiblePromotionsRequest {
    /**
     * serial of product
     * @type {Array<CampaignType>}
     * @memberof GetEligiblePromotionsRequest
     */
    campaignType: Array<CampaignType>;
    /**
     * @type {Segment}
     * @memberof GetEligiblePromotionsRequest
     */
    segment?: Segment;
    /**
     * @type {Language}
     * @memberof GetEligiblePromotionsRequest
     */
    language: Language;
}
