// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface GetPreToPostEligiblityRequest
 */
export interface GetPreToPostEligiblityRequest {
    /**
     * msisdn
     * @type {string}
     * @memberof GetPreToPostEligiblityRequest
     */
    msisdn: string;
    /**
     * last 4 digit of ICCID
     * @type {string}
     * @memberof GetPreToPostEligiblityRequest
     */
    last4SimDigits?: string;
    /**
     * puk
     * @type {string}
     * @memberof GetPreToPostEligiblityRequest
     */
    puk?: string;
}
