// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MobilePackLevel,
} from './';

/**
 * @export
 * @interface GetPackMigrationMatrixResponse
 */
export interface GetPackMigrationMatrixResponse {
    /**
     * @type {Array<MobilePackLevel>}
     * @memberof GetPackMigrationMatrixResponse
     */
    mobilePacks?: Array<MobilePackLevel>;
}
