// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Price,
} from './';

/**
 * @export
 * @interface HardwarePlanRate
 */
export interface HardwarePlanRate {
    /**
     * @type {Price}
     * @memberof HardwarePlanRate
     */
    finalInstallmentAmount?: Price;
    /**
     * @type {number}
     * @memberof HardwarePlanRate
     */
    installmentThresholdMonths?: number;
    /**
     * @type {Price}
     * @memberof HardwarePlanRate
     */
    oneTimeCharge?: Price;
    /**
     * @type {string}
     * @memberof HardwarePlanRate
     */
    product?: string;
    /**
     * @type {Price}
     * @memberof HardwarePlanRate
     */
    recurringCharge?: Price;
    /**
     * @type {number}
     * @memberof HardwarePlanRate
     */
    totalInstallmentMonths?: number;
}
