// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum IdentityType {
    L = 'L',
    N = 'N',
    B = 'B',
    C = 'C',
    CI = 'Ci',
    F = 'F',
    G = 'G',
    SWISS_LEGITIMATION_CARD = 'Swiss Legitimation Card',
    SWISS_DRIVING_LICENCE = 'Swiss Driving Licence',
    FOREIGN_PASSPORT = 'Foreign Passport',
    SWISS_IDENTITY_CARD = 'Swiss Identity Card',
    IDENTITY_CARD_GERMANY = 'Identity card Germany',
    IDENTITY_CARD_BELGIUM = 'Identity card Belgium',
    IDENTITY_CARD_FINLAND = 'Identity card Finland',
    IDENTITY_CARD_FRANCE = 'Identity card France',
    IDENTITY_CARD_GREECE = 'Identity card Greece',
    IDENTITY_CARD_ITALY = 'Identity card Italy',
    IDENTITY_CARD_LIECHTENSTEIN = 'Identity card Liechtenstein',
    IDENTITY_CARD_LUXEMBURG = 'Identity card Luxemburg',
    IDENTITY_CARD_MALTA = 'Identity card Malta',
    IDENTITY_CARD_MONACO = 'Identity card Monaco',
    IDENTITY_CARD_NETHERLANDS = 'Identity card Netherlands',
    IDENTITY_CARD_AUSTRIA = 'Identity card Austria',
    IDENTITY_CARD_PORTUGAL = 'Identity card Portugal',
    IDENTITY_CARD_SAN_MARINO = 'Identity card San Marino',
    IDENTITY_CARD_SPAIN = 'Identity card Spain',
    IDENTITY_CARD_BULGARIA = 'Identity card Bulgaria',
    IDENTITY_CARD_ESTONIA = 'Identity card Estonia',
    IDENTITY_CARD_CROATIA = 'Identity card Croatia',
    IDENTITY_CARD_LATVIA = 'Identity card Latvia',
    IDENTITY_CARD_LITHUANIA = 'Identity card Lithuania',
    IDENTITY_CARD_POLAND = 'Identity card Poland',
    IDENTITY_CARD_ROMANIA = 'Identity card Romania',
    IDENTITY_CARD_SLOVAKIA = 'Identity card Slovakia',
    IDENTITY_CARD_SLOVENIA = 'Identity card Slovenia',
    IDENTITY_CARD_CZECH_REPUBLIC = 'Identity card Czech Republic',
    IDENTITY_CARD_HUNGARY = 'Identity card Hungary',
    IDENTITY_CARD_SWEDEN = 'Identity card Sweden',
    SWISS_PASSPORT = 'Swiss Passport'
}

