// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface KeyValuePairType
 */
export interface KeyValuePairType {
    /**
     * key of additional attributes
     * @type {string}
     * @memberof KeyValuePairType
     */
    key: string;
    /**
     * value of additional attributes
     * @type {string}
     * @memberof KeyValuePairType
     */
    value: string;
}
