// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Layer,
    LineSpeed,
} from './';

/**
 * @export
 * @interface LayerCoverage
 */
export interface LayerCoverage {
    /**
     * @type {Layer}
     * @memberof LayerCoverage
     */
    layer?: Layer;
    /**
     * @type {LineSpeed}
     * @memberof LayerCoverage
     */
    indoor?: LineSpeed;
    /**
     * @type {LineSpeed}
     * @memberof LayerCoverage
     */
    outdoor?: LineSpeed;
}
