// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface LegalAddress
 */
export interface LegalAddress {
    /**
     * @type {string}
     * @memberof LegalAddress
     */
    additional?: string;
    /**
     * @type {string}
     * @memberof LegalAddress
     */
    country?: string;
    /**
     * @type {string}
     * @memberof LegalAddress
     */
    zip?: string;
    /**
     * @type {string}
     * @memberof LegalAddress
     */
    street?: string;
    /**
     * @type {string}
     * @memberof LegalAddress
     */
    house?: string;
    /**
     * @type {string}
     * @memberof LegalAddress
     */
    city?: string;
}
