// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ActionType,
} from './';

/**
 * @export
 * @interface LineItemTypeInput
 */
export interface LineItemTypeInput {
    /**
     * @type {ActionType}
     * @memberof LineItemTypeInput
     */
    actionType: ActionType;
    /**
     * name of rateplan
     * @type {string}
     * @memberof LineItemTypeInput
     */
    name: string;
}
