// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ActionType,
    PartSubType,
    PartType,
} from './';

/**
 * Use this to filter line item in the response
 * @export
 * @interface LineItemFilterType
 */
export interface LineItemFilterType {
    /**
     * @type {ActionType}
     * @memberof LineItemFilterType
     */
    actionType?: ActionType;
    /**
     * @type {PartSubType}
     * @memberof LineItemFilterType
     */
    partSubType?: PartSubType;
    /**
     * @type {PartType}
     * @memberof LineItemFilterType
     */
    partType?: PartType;
}
