// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    SpeedProfile,
} from './';

/**
 * @export
 * @interface LineSpeed
 */
export interface LineSpeed {
    /**
     * @type {number}
     * @memberof LineSpeed
     */
    maxBandwidthDown?: number;
    /**
     * @type {number}
     * @memberof LineSpeed
     */
    maxBandwidthUp?: number;
    /**
     * @type {Array<SpeedProfile>}
     * @memberof LineSpeed
     */
    speedProfiles?: Array<SpeedProfile>;
}
