// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AccessDescriptor,
    Language,
    LineCheckAddress,
    Segment,
    Technology,
} from './';

/**
 * @export
 * @interface LineCheckForNewActivationRequest
 */
export interface LineCheckForNewActivationRequest {
    /**
     * @type {string}
     * @memberof LineCheckForNewActivationRequest
     */
    lri?: string;
    /**
     * @type {LineCheckAddress}
     * @memberof LineCheckForNewActivationRequest
     */
    address?: LineCheckAddress;
    /**
     * @type {Array<AccessDescriptor>}
     * @memberof LineCheckForNewActivationRequest
     */
    accessDescriptors?: Array<AccessDescriptor>;
    /**
     * @type {Technology}
     * @memberof LineCheckForNewActivationRequest
     */
    technology?: Technology;
    /**
     * @type {Segment}
     * @memberof LineCheckForNewActivationRequest
     */
    segment: Segment;
    /**
     * @type {Array<string>}
     * @memberof LineCheckForNewActivationRequest
     */
    qualifyBundles?: Array<string>;
    /**
     * @type {Language}
     * @memberof LineCheckForNewActivationRequest
     */
    lang?: Language;
}
