// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface LineCheckAddress
 */
export interface LineCheckAddress {
    /**
     * @type {string}
     * @memberof LineCheckAddress
     */
    street: string;
    /**
     * @type {string}
     * @memberof LineCheckAddress
     */
    houseNr: string;
    /**
     * @type {string}
     * @memberof LineCheckAddress
     */
    city: string;
    /**
     * @type {string}
     * @memberof LineCheckAddress
     */
    zipcode: string;
}
