// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AccessProviderStatus,
    EligibleAccess,
    EligibleBundle,
    LineCheckAddress,
    Technology,
} from './';

/**
 * @export
 * @interface LineCheckEligibility
 */
export interface LineCheckEligibility {
    /**
     * @type {Array<EligibleBundle>}
     * @memberof LineCheckEligibility
     */
    eligibleBundles?: Array<EligibleBundle>;
    /**
     * @type {Array<string>}
     * @memberof LineCheckEligibility
     */
    qualifiedBundles?: Array<string>;
    /**
     * @type {Array<EligibleAccess>}
     * @memberof LineCheckEligibility
     */
    eligibleAccess?: Array<EligibleAccess>;
    /**
     * @type {Array<Technology>}
     * @memberof LineCheckEligibility
     */
    technologies?: Array<Technology>;
    /**
     * @type {LineCheckAddress}
     * @memberof LineCheckEligibility
     */
    address?: LineCheckAddress;
    /**
     * @type {string}
     * @memberof LineCheckEligibility
     */
    lri?: string;
    /**
     * @type {Array<AccessProviderStatus>}
     * @memberof LineCheckEligibility
     */
    accessProviderStatus?: Array<AccessProviderStatus>;
    /**
     * Fixnet Product serial
     * @type {string}
     * @memberof LineCheckEligibility
     */
    serial?: string;
}
