// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    RecommendationType,
    WeMobileLevel,
} from './';

/**
 * @export
 * @interface MobilePackLevel
 */
export interface MobilePackLevel {
    /**
     * @type {WeMobileLevel}
     * @memberof MobilePackLevel
     */
    packName?: WeMobileLevel;
    /**
     * @type {RecommendationType}
     * @memberof MobilePackLevel
     */
    recommendation?: RecommendationType;
}
