// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum MsisdnPortabilityStatus {
    OK = 'OK',
    ONP_NOT_ALLOWED = 'ONP_NOT_ALLOWED',
    MSISDN_NOT_RESERVABLE = 'MSISDN_NOT_RESERVABLE',
    RESELLER_MISMATCH = 'RESELLER_MISMATCH',
    TSP_MISMATCH = 'TSP_MISMATCH'
}

