// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MsisdnPortabilityStatus,
} from './';

/**
 * @export
 * @interface MsisdnPortabilityCheckResponse
 */
export interface MsisdnPortabilityCheckResponse {
    /**
     * @type {string}
     * @memberof MsisdnPortabilityCheckResponse
     */
    msisdn: string;
    /**
     * @type {boolean}
     * @memberof MsisdnPortabilityCheckResponse
     */
    eligible?: boolean;
    /**
     * @type {string}
     * @memberof MsisdnPortabilityCheckResponse
     */
    tspId?: string;
    /**
     * @type {string}
     * @memberof MsisdnPortabilityCheckResponse
     */
    resellerId?: string;
    /**
     * @type {string}
     * @memberof MsisdnPortabilityCheckResponse
     */
    resellerName?: string;
    /**
     * @type {boolean}
     * @memberof MsisdnPortabilityCheckResponse
     */
    prepaidReseller?: boolean;
    /**
     * @type {boolean}
     * @memberof MsisdnPortabilityCheckResponse
     */
    postpaidReseller?: boolean;
    /**
     * @type {MsisdnPortabilityStatus}
     * @memberof MsisdnPortabilityCheckResponse
     */
    eligibilityStatus?: MsisdnPortabilityStatus;
}
