// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Model for notification details
 * @export
 * @interface NotificationReference
 */
export interface NotificationReference {
    /**
     * customer email on which order will be sent
     * @type {string}
     * @memberof NotificationReference
     */
    email?: string;
    /**
     * customer phone number
     * @type {string}
     * @memberof NotificationReference
     */
    phoneNumber?: string;
}
