// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum OfferPrintStatusType {
    OK = 'OK',
    CREATE_OFFER_NOK = 'CREATE_OFFER_NOK',
    CREATE_APPOINTMENT_NOK = 'CREATE_APPOINTMENT_NOK',
    PRINT_ORDER_NOK = 'PRINT_ORDER_NOK',
    EMAIL_ORDER_NOK = 'EMAIL_ORDER_NOK'
}

