// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Addressee,
    CompanyDetailsInput,
    Contact,
    Segment,
} from './';

/**
 * @export
 * @interface OfferCustomer
 */
export interface OfferCustomer {
    /**
     * @type {string}
     * @memberof OfferCustomer
     */
    customerId?: string;
    /**
     * @type {CompanyDetailsInput}
     * @memberof OfferCustomer
     */
    companyDetails?: CompanyDetailsInput;
    /**
     * @type {Contact}
     * @memberof OfferCustomer
     */
    legalContact?: Contact;
    /**
     * @type {Addressee}
     * @memberof OfferCustomer
     */
    legalAddressee?: Addressee;
    /**
     * @type {Segment}
     * @memberof OfferCustomer
     */
    segment: Segment;
}
