// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BundleTemplate,
    FirmCategory,
    Price,
    ProcessType,
    Product,
    SpecialFields,
} from './';

/**
 * @export
 * @interface OrderEntry
 */
export interface OrderEntry {
    /**
     * @type {number}
     * @memberof OrderEntry
     */
    bundleNo?: number;
    /**
     * @type {Product}
     * @memberof OrderEntry
     */
    product?: Product;
    /**
     * @type {BundleTemplate}
     * @memberof OrderEntry
     */
    component?: BundleTemplate;
    /**
     * @type {Price}
     * @memberof OrderEntry
     */
    totalPrice?: Price;
    /**
     * @type {Array<Price>}
     * @memberof OrderEntry
     */
    totalRecurringCharges?: Array<Price>;
    /**
     * @type {Array<SpecialFields>}
     * @memberof OrderEntry
     */
    specialFields?: Array<SpecialFields>;
    /**
     * @type {number}
     * @memberof OrderEntry
     */
    entryNumber: number;
    /**
     * @type {string}
     * @memberof OrderEntry
     */
    appliedVoucher?: string;
    /**
     * @type {ProcessType}
     * @memberof OrderEntry
     */
    processType?: ProcessType;
    /**
     * @type {BundleTemplate}
     * @memberof OrderEntry
     */
    rootBundleTemplate?: BundleTemplate;
    /**
     * @type {FirmCategory}
     * @memberof OrderEntry
     */
    firmCategory?: FirmCategory;
}
