// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum OrderType {
    NEW = 'NEW',
    CEASE = 'CEASE',
    TRANSFER = 'TRANSFER',
    RELOCATION = 'RELOCATION',
    CONVERSION = 'CONVERSION',
    MODIFY = 'MODIFY',
    RECONNECT = 'RECONNECT',
    MIGRATION = 'MIGRATION',
    RETURN = 'RETURN',
    SUSPEND = 'SUSPEND',
    UNSUSPEND = 'UNSUSPEND',
    UPGRADE_OR_DOWNGRADE = 'UPGRADE_OR_DOWNGRADE'
}

