// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PartType {
    BILLING_CODE = 'Billing Code',
    POSTPAID_BILLING_SERVICE = 'Postpaid Billing Service',
    BILLING_SERVICE = 'Billing Service',
    DATA = 'Data',
    DEPOSIT_PLAN = 'Deposit Plan',
    MAIN_CONTRACT = 'Main Contract',
    MAIN_PART = 'Main Part',
    OPTION = 'Option',
    COMMERCIAL_PRODUCT = 'Commercial Product',
    RATE_PLAN = 'Rate Plan',
    VOICEMAIL = 'Voicemail',
    COST_MANAGER = 'cost manager',
    PUBLIC_TPV = 'Public TPV',
    DISCOUNT = 'Discount',
    DOWNGRADE_FEE = 'Downgrade Fee',
    ETF = 'ETF',
    HARDWARE = 'Hardware',
    INFO = 'Info',
    NETWORK = 'Network',
    NOT_APPLICABLE = 'Not Applicable',
    OTHER = 'Other',
    PROMOTION = 'Promotion',
    ACCESS = 'Access',
    ACCESS_OPTION = 'Access Option',
    ACCESS_SUBOPTION = 'Access Suboption',
    VOICE = 'Voice',
    SETUP_FEE = 'Setup Fee',
    TEASER = 'Teaser',
    INSTALMENT = 'Instalment',
    BUNDLE_BILLING_SERVICE = 'Bundle Billing Service',
    LOYALTY = 'Loyalty',
    ADD_ON = 'Add-on',
    PCRF_RP = 'PCRF RP',
    CHARGES = 'Charges',
    MOBILE_PACK_LINE_ITEM = 'Mobile Pack Line Item',
    OTT_TV_SERVICE = 'OTT TV Service',
    SUBSCRIPTION_PACK = 'Subscription Pack',
    NET_PAYMENT_SERVICE = 'Net Payment Service',
    SERVICE = 'Service'
}

