// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    KeyValuePairType,
    PartType,
    ProductOptionSubType,
} from './';

/**
 * @export
 * @interface PartInfoType
 */
export interface PartInfoType {
    /**
     * @type {string}
     * @memberof PartInfoType
     */
    name: string;
    /**
     * @type {string}
     * @memberof PartInfoType
     */
    partStatus: string;
    /**
     * @type {string}
     * @memberof PartInfoType
     */
    installDate: string;
    /**
     * @type {string}
     * @memberof PartInfoType
     */
    deinstallDate?: string;
    /**
     * If current discount was installed by some promotion, its name should be shown here.
     * @type {string}
     * @memberof PartInfoType
     */
    campaignName?: string;
    /**
     * @type {ProductOptionSubType}
     * @memberof PartInfoType
     */
    partSubType?: ProductOptionSubType;
    /**
     * Negative monetary amount in case of recurring discount.
     * @type {number}
     * @memberof PartInfoType
     */
    calculatedAmountChf?: number;
    /**
     * @type {PartType}
     * @memberof PartInfoType
     */
    partType?: PartType;
    /**
     * @type {Array<PartInfoType>}
     * @memberof PartInfoType
     */
    childItems?: Array<PartInfoType>;
    /**
     * @type {Array<KeyValuePairType>}
     * @memberof PartInfoType
     */
    attributes?: Array<KeyValuePairType>;
}
