// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PartSubType {
    FMC_DISCOUNT = 'FMC discount',
    SUNRISE_ADVANTAGE_DISCOUNT = 'Sunrise Advantage discount',
    LOYALTY_DISCOUNT = 'Loyalty discount',
    YOUNG_DISCOUNT = 'Young discount',
    BINDING_PROMO_DISCOUNT = 'Binding promo discount',
    FO_F_DISCOUNT = 'FoF discount',
    EO_F_DISCOUNT = 'EoF discount',
    CASHBACK = 'Cashback',
    WE_BENEFIT = 'We benefit',
    SUBSIDIZED_HW = 'Subsidized HW',
    HARDWARE_GIFT = 'Hardware Gift',
    VOUCHER = 'Voucher',
    MRC_DISCOUNT = 'MRC Discount'
}

