// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BillingTime,
    Discount,
    PriceValue,
} from './';

/**
 * @export
 * @interface Price
 */
export interface Price {
    /**
     * @type {BillingTime}
     * @memberof Price
     */
    billingTime?: BillingTime;
    /**
     * @type {string}
     * @memberof Price
     */
    currencyIso?: string;
    /**
     * @type {Array<Discount>}
     * @memberof Price
     */
    discounts?: Array<Discount>;
    /**
     * @type {PriceValue}
     * @memberof Price
     */
    originalPrice?: PriceValue;
    /**
     * @type {PriceValue}
     * @memberof Price
     */
    price?: PriceValue;
    /**
     * @type {number}
     * @memberof Price
     */
    value?: number;
    /**
     * @type {string}
     * @memberof Price
     */
    priceType?: string;
}
