// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PriceBundleRule
 */
export interface PriceBundleRule {
    /**
     * @type {string}
     * @memberof PriceBundleRule
     */
    id?: string;
    /**
     * @type {number}
     * @memberof PriceBundleRule
     */
    price?: number;
    /**
     * @type {number}
     * @memberof PriceBundleRule
     */
    discountPrice?: number;
    /**
     * @type {Array<string>}
     * @memberof PriceBundleRule
     */
    targetProducts?: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof PriceBundleRule
     */
    targetParentProducts?: Array<string>;
}
