// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PriceOfferResponseTypeErrorCode {
    RP_PACK_LEVEL_MISMATCH = 'RP_PACK_LEVEL_MISMATCH',
    INVALID_PACK_LEVEL = 'INVALID_PACK_LEVEL',
    ORDERED_AS_FIRST_ALREADY_EXISTS = 'ORDERED_AS_FIRST_ALREADY_EXISTS'
}

