// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProcessType {
    NEW = 'NEW',
    DEVICE_ON_EXISTING = 'DEVICE_ON_EXISTING',
    MODIFY = 'MODIFY',
    DEVICE_ONLY = 'DEVICE_ONLY',
    PRE_TO_POST = 'PRE_TO_POST'
}

