// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    LineItemTypeInput,
    OrderType,
} from './';

/**
 * @export
 * @interface ProductPriceOfferRequestType
 */
export interface ProductPriceOfferRequestType {
    /**
     * Contract Extension or not
     * @type {boolean}
     * @memberof ProductPriceOfferRequestType
     */
    contractExtension?: boolean;
    /**
     * duration
     * @type {number}
     * @memberof ProductPriceOfferRequestType
     */
    duration?: number;
    /**
     * index of order
     * @type {string}
     * @memberof ProductPriceOfferRequestType
     */
    orderIndex: string;
    /**
     * @type {OrderType}
     * @memberof ProductPriceOfferRequestType
     */
    orderType: OrderType;
    /**
     * @type {Array<LineItemTypeInput>}
     * @memberof ProductPriceOfferRequestType
     */
    lineItems?: Array<LineItemTypeInput>;
    /**
     * product name
     * @type {string}
     * @memberof ProductPriceOfferRequestType
     */
    productName: string;
    /**
     * product Serial
     * @type {string}
     * @memberof ProductPriceOfferRequestType
     */
    serial?: string;
}
