// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BundleTemplate,
    Color,
    Entitlement,
    HardwarePlanRate,
    Memory,
    Picture,
    Price,
    ProductReference,
    PromotionInfo,
    SubscriptionTerm,
    SunCodeListEntry,
} from './';

/**
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * @type {string}
     * @memberof Product
     */
    availability?: string;
    /**
     * @type {string}
     * @memberof Product
     */
    code?: string;
    /**
     * @type {Array<Entitlement>}
     * @memberof Product
     */
    entitlements?: Array<Entitlement>;
    /**
     * @type {Array<Entitlement>}
     * @memberof Product
     */
    greyedOutEntitlements?: Array<Entitlement>;
    /**
     * @type {string}
     * @memberof Product
     */
    description?: string;
    /**
     * @type {string}
     * @memberof Product
     */
    group?: string;
    /**
     * @type {boolean}
     * @memberof Product
     */
    isYoungProduct?: boolean;
    /**
     * @type {string}
     * @memberof Product
     */
    oneLineTitle?: string;
    /**
     * @type {Array<Price>}
     * @memberof Product
     */
    oneTimeCharges?: Array<Price>;
    /**
     * @type {Price}
     * @memberof Product
     */
    downPayment?: Price;
    /**
     * @type {Array<HardwarePlanRate>}
     * @memberof Product
     */
    hardwarePlansRate?: Array<HardwarePlanRate>;
    /**
     * @type {string}
     * @memberof Product
     */
    name?: string;
    /**
     * @type {Product}
     * @memberof Product
     */
    parentProduct?: Product;
    /**
     * @type {Picture}
     * @memberof Product
     */
    picture?: Picture;
    /**
     * @type {Price}
     * @memberof Product
     */
    price?: Price;
    /**
     * @type {SunCodeListEntry}
     * @memberof Product
     */
    productType?: SunCodeListEntry;
    /**
     * @type {Array<PromotionInfo>}
     * @memberof Product
     */
    promotionInfo?: Array<PromotionInfo>;
    /**
     * @type {string}
     * @memberof Product
     */
    promoText1?: string;
    /**
     * @type {string}
     * @memberof Product
     */
    promoText2?: string;
    /**
     * @type {Array<Price>}
     * @memberof Product
     */
    recurringCharges?: Array<Price>;
    /**
     * @type {string}
     * @memberof Product
     */
    subGroup?: string;
    /**
     * @type {SubscriptionTerm}
     * @memberof Product
     */
    subscriptionTerm?: SubscriptionTerm;
    /**
     * @type {Array<ProductReference>}
     * @memberof Product
     */
    productReferences?: Array<ProductReference>;
    /**
     * @type {Color}
     * @memberof Product
     */
    color?: Color;
    /**
     * @type {string}
     * @memberof Product
     */
    manufacturer?: string;
    /**
     * @type {Memory}
     * @memberof Product
     */
    memory?: Memory;
    /**
     * @type {Array<BundleTemplate>}
     * @memberof Product
     */
    bundleTemplates?: Array<BundleTemplate>;
    /**
     * @type {Array<BundleTemplate>}
     * @memberof Product
     */
    defaultBundleTemplates?: Array<BundleTemplate>;
    /**
     * @type {number}
     * @memberof Product
     */
    babsiDiscount?: number;
    /**
     * @type {string}
     * @memberof Product
     */
    babsiPromoText?: string;
    /**
     * @type {Array<Entitlement>}
     * @memberof Product
     */
    keyFeatures?: Array<Entitlement>;
}
