// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    RecommendationType,
} from './';

/**
 * @export
 * @interface ProductType
 */
export interface ProductType {
    /**
     * binding promo name for the product
     * @type {string}
     * @memberof ProductType
     */
    bindingPromoName?: string;
    /**
     * binding promo violation
     * @type {boolean}
     * @memberof ProductType
     */
    bindingPromoViolated?: boolean | null;
    /**
     * eligible for discount or not
     * @type {boolean}
     * @memberof ProductType
     */
    discountEligible?: boolean;
    /**
     * earliest product Migration Date
     * @type {string}
     * @memberof ProductType
     */
    earliestMigrationDate?: string | null;
    /**
     * migration fee
     * @type {number}
     * @memberof ProductType
     */
    migrationFee: number;
    /**
     * product name
     * @type {string}
     * @memberof ProductType
     */
    productName: string;
    /**
     * @type {RecommendationType}
     * @memberof ProductType
     */
    recommendation?: RecommendationType;
    /**
     * product transition
     * @type {string}
     * @memberof ProductType
     */
    transition: string;
}
