// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProductSubGroup {
    ADSL = 'ADSL',
    BUNDLE = 'BUNDLE',
    BUSINESS_CLOUD_PBX = 'BUSINESS_CLOUD_PBX',
    BUSINESS_INTERNET_DIRECT_BBCS_CU = 'BUSINESS_INTERNET_DIRECT_BBCS_CU',
    BUSINESS_INTERNET_DIRECT_BBCS_F = 'BUSINESS_INTERNET_DIRECT_BBCS_F',
    DATACARD = 'DATACARD',
    DATA_POSTPAID = 'DATA_POSTPAID',
    DATA_POSTPAID_PLAN = 'DATA_POSTPAID_PLAN',
    DATA_PREPAID = 'DATA_PREPAID',
    DDI = 'DDI',
    FIBER = 'FIBER',
    INDOORBOX = 'INDOORBOX',
    INTERNET = 'INTERNET',
    ISDN = 'ISDN',
    MOBILE_PLAN_UNLIMITED = 'MOBILE_PLAN_UNLIMITED',
    NONE = 'NONE',
    PARENT = 'PARENT',
    PBX_CLOUD = 'PBX_CLOUD',
    PBX_LOCAL = 'PBX_LOCAL',
    POSTPAID = 'POSTPAID',
    POSTPAID_LIGHT = 'POSTPAID_LIGHT',
    POSTPAID_PLAN = 'POSTPAID_PLAN',
    PREPAID = 'PREPAID',
    SDSL = 'SDSL',
    SECURITY = 'SECURITY',
    SELECT = 'SELECT',
    TV = 'TV',
    TV_APP = 'TV_APP',
    TV_LIGHT = 'TV_LIGHT',
    TV_HZN = 'TV_HZN',
    UNLIMITED = 'UNLIMITED',
    VDSL = 'VDSL',
    VOICE = 'VOICE',
    VOICE_DDI = 'VOICE_DDI',
    VOICE_INTERNET = 'VOICE_INTERNET',
    VOICE_ISDN = 'VOICE_ISDN'
}

