// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProductOptionSubType {
    INTERNET = 'INTERNET',
    TV = 'TV',
    VOICE = 'VOICE',
    MOBILE = 'MOBILE',
    OTHER = 'OTHER',
    PBX = 'PBX',
    DATA = 'DATA',
    HZN_TV = 'HZN_TV',
    OTT_TV = 'OTT_TV'
}

