// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    KeyValuePairType,
    LineItemType,
    PriceOfferResponseTypeErrorCode,
} from './';

/**
 * @export
 * @interface ProductPriceOfferResponseType
 */
export interface ProductPriceOfferResponseType {
    /**
     * @type {PriceOfferResponseTypeErrorCode}
     * @memberof ProductPriceOfferResponseType
     */
    errorCode?: PriceOfferResponseTypeErrorCode;
    /**
     * Is First Subscription of mobile pack
     * @type {boolean}
     * @memberof ProductPriceOfferResponseType
     */
    isMobilePackFirstSubscription?: boolean | null;
    /**
     * @type {Array<LineItemType>}
     * @memberof ProductPriceOfferResponseType
     */
    lineItems?: Array<LineItemType>;
    /**
     * @type {Array<KeyValuePairType>}
     * @memberof ProductPriceOfferResponseType
     */
    orderAttributes?: Array<KeyValuePairType>;
    /**
     * index of order
     * @type {string}
     * @memberof ProductPriceOfferResponseType
     */
    orderIndex?: string;
    /**
     * product name
     * @type {string}
     * @memberof ProductPriceOfferResponseType
     */
    productName?: string;
    /**
     * order quation id
     * @type {string}
     * @memberof ProductPriceOfferResponseType
     */
    quotationId?: string;
    /**
     * sales Id
     * @type {string}
     * @memberof ProductPriceOfferResponseType
     */
    salesId?: string;
    /**
     * product Serial
     * @type {string}
     * @memberof ProductPriceOfferResponseType
     */
    serial?: string;
}
