// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Facet,
    Pagination,
    Product,
} from './';

/**
 * @export
 * @interface ProductSearchResponse
 */
export interface ProductSearchResponse {
    /**
     * @type {Array<Facet>}
     * @memberof ProductSearchResponse
     */
    facets?: Array<Facet>;
    /**
     * @type {Pagination}
     * @memberof ProductSearchResponse
     */
    pagination?: Pagination;
    /**
     * @type {Array<Product>}
     * @memberof ProductSearchResponse
     */
    products?: Array<Product>;
}
