// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProductGroup {
    BUSINESS_COMPANY = 'BUSINESS_COMPANY',
    BUS_FIXNET = 'BUS_FIXNET',
    BUS_FIX_INTERNET = 'BUS_FIX_INTERNET',
    BUS_FIX_VOICE = 'BUS_FIX_VOICE',
    FIXNET = 'FIXNET',
    FIXNET_APP = 'FIXNET_APP',
    HOME = 'HOME',
    HOME_UNLIMITED = 'HOME_UNLIMITED',
    MOBILE = 'MOBILE',
    MOBILE_COVERAGE = 'MOBILE_COVERAGE',
    MOBILE_WEARABLE = 'MOBILE_WEARABLE',
    MTV_HOME = 'MTV_HOME',
    OFFICE_PRO = 'OFFICE_PRO',
    OFFICE_PRO_LIGHT = 'OFFICE_PRO_LIGHT',
    PRODUCT = 'PRODUCT',
    SOLUTION = 'SOLUTION',
    TOOLS = 'TOOLS',
    WE_HOME = 'WE_HOME',
    WE_HOME_PLUS = 'WE_HOME_PLUS',
    WE_HOME_PLUS_PLUS = 'WE_HOME_PLUS_PLUS',
    WE_MOBILE_NON_PACK = 'WE_MOBILE_NON_PACK',
    WE_MOBILE_PACK_L = 'WE_MOBILE_PACK_L',
    WE_MOBILE_PACK_M = 'WE_MOBILE_PACK_M',
    WE_MOBILE_PACK_XL = 'WE_MOBILE_PACK_XL',
    WE_MOBILE = 'WE_MOBILE',
    MOBILE_LIGHT = 'MOBILE_LIGHT',
    MOBILE_PREPAID = 'MOBILE_PREPAID',
    MOBILE_POSTPAID = 'MOBILE_POSTPAID',
    FIX_INTERNET = 'FIX_INTERNET'
}

