// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProfileTech {
    ADSL = 'ADSL',
    ADSL2PLUS = 'ADSL2plus',
    ADSL2PLUS_M = 'ADSL2plusM',
    SHDSL = 'SHDSL',
    SHDS_LBIS = 'SHDSLbis',
    SHDSL_PACKET_MODE = 'SHDSLPacketMode',
    SHDS_LBIS_PACKET_MODE = 'SHDSLbisPacketMode'
}

