// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PromotionDiscount
 */
export interface PromotionDiscount {
    /**
     * @type {string}
     * @memberof PromotionDiscount
     */
    device?: string;
    /**
     * @type {number}
     * @memberof PromotionDiscount
     */
    discountPrice?: number;
    /**
     * @type {boolean}
     * @memberof PromotionDiscount
     */
    promotionEnabled?: boolean;
    /**
     * @type {number}
     * @memberof PromotionDiscount
     */
    regularPrice?: number;
    /**
     * @type {string}
     * @memberof PromotionDiscount
     */
    subscription?: string;
}
