// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PromotionInfo
 */
export interface PromotionInfo {
    /**
     * @type {number}
     * @memberof PromotionInfo
     */
    discountAmount?: number;
    /**
     * @type {number}
     * @memberof PromotionInfo
     */
    installmentWithPromo?: number;
    /**
     * @type {number}
     * @memberof PromotionInfo
     */
    lastInstallmentWithPromo?: number;
    /**
     * @type {string}
     * @memberof PromotionInfo
     */
    promoId?: string;
    /**
     * @type {Array<string>}
     * @memberof PromotionInfo
     */
    targetedFor?: Array<string>;
    /**
     * @type {string}
     * @memberof PromotionInfo
     */
    type?: string;
}
