// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Promotion,
    PromotionOrderEntryConsumed,
} from './';

/**
 * @export
 * @interface PromotionResult
 */
export interface PromotionResult {
    /**
     * @type {string}
     * @memberof PromotionResult
     */
    description?: string;
    /**
     * @type {Array<PromotionOrderEntryConsumed>}
     * @memberof PromotionResult
     */
    consumedEntries?: Array<PromotionOrderEntryConsumed>;
    /**
     * @type {Promotion}
     * @memberof PromotionResult
     */
    promotion?: Promotion;
}
