// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PromotionOrderEntryConsumed
 */
export interface PromotionOrderEntryConsumed {
    /**
     * @type {number}
     * @memberof PromotionOrderEntryConsumed
     */
    adjustedUnitPrice: number;
    /**
     * @type {string}
     * @memberof PromotionOrderEntryConsumed
     */
    code?: string;
    /**
     * @type {number}
     * @memberof PromotionOrderEntryConsumed
     */
    orderEntryNumber: number;
    /**
     * @type {number}
     * @memberof PromotionOrderEntryConsumed
     */
    quantity: number;
}
