// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum QualificationType {
    QUALIFICATION_BY_ADDRESS = 'QualificationByAddress',
    QUALIFICATION_BY_OTO_ID = 'QualificationByOtoId',
    QUALIFICATION_BY_ACTIVE_CLI = 'QualificationByActiveCli',
    QUALIFICATION_BY_PRE_CLI = 'QualificationByPreCli',
    QUALIFICATION_BY_LRI = 'QualificationByLri'
}

