// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum RatePlanType {
    MOBILE_PREPAID = 'MOBILE_PREPAID',
    MOBILE_POSTPAID = 'MOBILE_POSTPAID',
    TV = 'TV',
    HZN_TV = 'HZN_TV',
    LANDLINE_PHONE = 'LANDLINE_PHONE',
    FIX_INTERNET = 'FIX_INTERNET',
    MOBILE_COVERAGE = 'MOBILE_COVERAGE',
    OTT_TV = 'OTT_TV',
    UNDEFINED = 'UNDEFINED'
}

