// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface RecommendationType
 */
export interface RecommendationType {
    /**
     * recommended flag
     * @type {boolean}
     * @memberof RecommendationType
     */
    isRecommended?: boolean;
    /**
     * recommended campaign name
     * @type {string}
     * @memberof RecommendationType
     */
    recommendedCampaign?: string;
    /**
     * recommended product name
     * @type {string}
     * @memberof RecommendationType
     */
    recommendedProduct?: string;
}
