// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AccessDescriptor,
} from './';

/**
 * @export
 * @interface ServiceAccess
 */
export interface ServiceAccess {
    /**
     * @type {string}
     * @memberof ServiceAccess
     */
    product?: string;
    /**
     * @type {AccessDescriptor}
     * @memberof ServiceAccess
     */
    descriptor?: AccessDescriptor;
    /**
     * @type {string}
     * @memberof ServiceAccess
     */
    identifier?: string;
}
