// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AccountContact,
    AccountRatePlan,
    Address,
    Contract,
    RelationType,
    ServiceAccess,
    SubscriptionState,
} from './';

/**
 * @export
 * @interface Service
 */
export interface Service {
    /**
     * @type {string}
     * @memberof Service
     */
    serviceId?: string;
    /**
     * @type {string}
     * @memberof Service
     */
    name?: string;
    /**
     * @type {number}
     * @memberof Service
     */
    balance?: number | null;
    /**
     * @type {RelationType}
     * @memberof Service
     */
    relationType?: RelationType;
    /**
     * @type {SubscriptionState}
     * @memberof Service
     */
    fixnetSubscriptionState?: SubscriptionState;
    /**
     * @type {SubscriptionState}
     * @memberof Service
     */
    postpaidSubscriptionState?: SubscriptionState;
    /**
     * @type {Address}
     * @memberof Service
     */
    installationAddress?: Address;
    /**
     * @type {string}
     * @memberof Service
     */
    otoId?: string;
    /**
     * @type {string}
     * @memberof Service
     */
    unverifiedOtoId?: string;
    /**
     * @type {Contract}
     * @memberof Service
     */
    contract?: Contract;
    /**
     * @type {string}
     * @memberof Service
     */
    status?: string;
    /**
     * @type {AccountContact}
     * @memberof Service
     */
    contact?: AccountContact;
    /**
     * @type {Array<AccountRatePlan>}
     * @memberof Service
     */
    ratePlans?: Array<AccountRatePlan>;
    /**
     * @type {ServiceAccess}
     * @memberof Service
     */
    access?: ServiceAccess;
}
