// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ServiceSubType {
    PREPAID = 'PREPAID',
    POSTPAID = 'POSTPAID',
    POSTPAID_PLAN = 'POSTPAID_PLAN',
    DATA_POSTPAID = 'DATA_POSTPAID',
    DATA_POSTPAID_PLAN = 'DATA_POSTPAID_PLAN',
    DATA_PREPAID = 'DATA_PREPAID',
    DATACARD = 'DATACARD',
    MOBILE_PLAN_UNLIMITED = 'MOBILE_PLAN_UNLIMITED',
    POSTPAID_LIGHT = 'POSTPAID_LIGHT',
    VOICE = 'VOICE',
    VOICE_INTERNET = 'VOICE_INTERNET',
    INTERNET = 'INTERNET',
    TV = 'TV',
    MOBILE_POSTPAID_BABSI = 'MOBILE_POSTPAID_BABSI',
    MOBILE_POSTPAID_BABSI_CLASSIC = 'MOBILE_POSTPAID_BABSI_CLASSIC'
}

