// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ServicePlanEligibleStatus {
    OK = 'OK',
    DATE_FUTURE = 'DATE_FUTURE',
    PREPAID_BALANCE = 'PREPAID_BALANCE',
    EXISTING_ORDER = 'EXISTING_ORDER',
    PAID_INSTALLMENT = 'PAID_INSTALLMENT'
}

