// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ProfileTech,
} from './';

/**
 * @export
 * @interface SpeedProfile
 */
export interface SpeedProfile {
    /**
     * @type {ProfileTech}
     * @memberof SpeedProfile
     */
    profileTech?: ProfileTech;
    /**
     * @type {number}
     * @memberof SpeedProfile
     */
    bandwidthDown?: number;
    /**
     * @type {number}
     * @memberof SpeedProfile
     */
    bandwidthUp?: number;
    /**
     * @type {number}
     * @memberof SpeedProfile
     */
    lineCount?: number;
}
