// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface StartPoint
 */
export interface StartPoint {
    /**
     * @type {number}
     * @memberof StartPoint
     */
    taxRegion?: number;
    /**
     * @type {string}
     * @memberof StartPoint
     */
    accessNet?: string;
    /**
     * @type {number}
     * @memberof StartPoint
     */
    unitType?: number;
    /**
     * @type {number}
     * @memberof StartPoint
     */
    unitNumber?: number;
    /**
     * @type {number}
     * @memberof StartPoint
     */
    sse?: number;
    /**
     * @type {number}
     * @memberof StartPoint
     */
    contactType?: number;
    /**
     * @type {number}
     * @memberof StartPoint
     */
    contactNr?: number;
}
