// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SubscriptionState {
    ACTIVE = 'ACTIVE',
    ACTIVE_INT_LOW = 'ACTIVE_INT_LOW',
    INACTIVE = 'INACTIVE',
    SUSPENDED_BY_USER = 'SUSPENDED_BY_USER',
    SUSPENDED_BY_OPERATOR = 'SUSPENDED_BY_OPERATOR',
    DEACTIVE = 'DEACTIVE',
    TERMINATED = 'TERMINATED'
}

