// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum UIDStatus {
    UID_CHECKED = 'UID_CHECKED',
    BC_EXCEPTION = 'BC_EXCEPTION',
    BC_GOVERNANCE = 'BC_GOVERNANCE'
}

