// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Language,
    UserAction,
} from './';

/**
 * @export
 * @interface UpdateCartRequest
 */
export interface UpdateCartRequest {
    /**
     * @type {Array<UserAction>}
     * @memberof UpdateCartRequest
     */
    userActions: Array<UserAction>;
    /**
     * @type {Language}
     * @memberof UpdateCartRequest
     */
    lang?: Language;
}
