// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UpsellHomeBundle
 */
export interface UpsellHomeBundle {
    /**
     * @type {Array<string>}
     * @memberof UpsellHomeBundle
     */
    ratePlans?: Array<string>;
    /**
     * @type {number}
     * @memberof UpsellHomeBundle
     */
    points?: number;
    /**
     * @type {number}
     * @memberof UpsellHomeBundle
     */
    rank?: number;
}
