// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UpsellMobileRatePlan
 */
export interface UpsellMobileRatePlan {
    /**
     * @type {number}
     * @memberof UpsellMobileRatePlan
     */
    points?: number;
    /**
     * @type {number}
     * @memberof UpsellMobileRatePlan
     */
    rank?: number;
    /**
     * @type {string}
     * @memberof UpsellMobileRatePlan
     */
    ratePlan?: string;
}
