// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    UpsellHomeRatePlan,
    UpsellMobileRatePlan,
} from './';

/**
 * @export
 * @interface UpsellProductResponse
 */
export interface UpsellProductResponse {
    /**
     * @type {Array<UpsellMobileRatePlan>}
     * @memberof UpsellProductResponse
     */
    mobileRatePlans?: Array<UpsellMobileRatePlan>;
    /**
     * @type {Array<UpsellHomeRatePlan>}
     * @memberof UpsellProductResponse
     */
    homeRatePlans?: Array<UpsellHomeRatePlan>;
    /**
     * @type {string}
     * @memberof UpsellProductResponse
     */
    status?: string;
    /**
     * @type {string}
     * @memberof UpsellProductResponse
     */
    siteId?: string;
}
