// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    UpsellHomeBundle,
} from './';

/**
 * @export
 * @interface UpsellHomeRatePlan
 */
export interface UpsellHomeRatePlan {
    /**
     * @type {string}
     * @memberof UpsellHomeRatePlan
     */
    cli?: string;
    /**
     * @type {string}
     * @memberof UpsellHomeRatePlan
     */
    serviceId?: string;
    /**
     * @type {Array<UpsellHomeBundle>}
     * @memberof UpsellHomeRatePlan
     */
    bundles?: Array<UpsellHomeBundle>;
}
