// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UserAction
 */
export interface UserAction {
    /**
     * @type {string}
     * @memberof UserAction
     */
    action: string;
    /**
     * @type {string}
     * @memberof UserAction
     */
    componentCode: string;
    /**
     * @type {string}
     * @memberof UserAction
     */
    productCode: string;
    /**
     * @type {string}
     * @memberof UserAction
     */
    segmentCode: string;
}
