// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ValidateServiceSettingRequestValueType,
} from './';

/**
 * @export
 * @interface ValidateServiceSettingRequest
 */
export interface ValidateServiceSettingRequest {
    /**
     * @type {string}
     * @memberof ValidateServiceSettingRequest
     */
    value: string;
    /**
     * @type {ValidateServiceSettingRequestValueType}
     * @memberof ValidateServiceSettingRequest
     */
    valueType: ValidateServiceSettingRequestValueType;
}
