// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    LineCheckAddress,
    OfferCustomer,
    QualificationType,
    ValidateOfferProducts,
} from './';

/**
 * @export
 * @interface ValidateOfferResponse
 */
export interface ValidateOfferResponse {
    /**
     * @type {Array<ValidateOfferProducts>}
     * @memberof ValidateOfferResponse
     */
    products?: Array<ValidateOfferProducts>;
    /**
     * @type {string}
     * @memberof ValidateOfferResponse
     */
    cartId?: string;
    /**
     * @type {LineCheckAddress}
     * @memberof ValidateOfferResponse
     */
    address?: LineCheckAddress;
    /**
     * @type {QualificationType}
     * @memberof ValidateOfferResponse
     */
    type?: QualificationType;
    /**
     * @type {OfferCustomer}
     * @memberof ValidateOfferResponse
     */
    customer?: OfferCustomer;
    /**
     * @type {string}
     * @memberof ValidateOfferResponse
     */
    lri?: string;
    /**
     * @type {string}
     * @memberof ValidateOfferResponse
     */
    errorId?: string;
}
