// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AllocationIdentifier,
    Voucher,
} from './';

/**
 * @export
 * @interface VoucherAllocation
 */
export interface VoucherAllocation {
    /**
     * @type {AllocationIdentifier}
     * @memberof VoucherAllocation
     */
    targetAllocationIdentifier?: AllocationIdentifier;
    /**
     * @type {Voucher}
     * @memberof VoucherAllocation
     */
    voucher?: Voucher;
}
