// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    WeMobileLevel,
    WeMobileStatus,
} from './';

/**
 * @export
 * @interface WeMobile
 */
export interface WeMobile {
    /**
     * @type {WeMobileLevel}
     * @memberof WeMobile
     */
    level?: WeMobileLevel;
    /**
     * @type {WeMobileStatus}
     * @memberof WeMobile
     */
    status?: WeMobileStatus;
    /**
     * @type {string}
     * @memberof WeMobile
     */
    startDate?: string | null;
}
