// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, HttpQuery, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    Account,
    WeBenefitInfo,
} from '../models';

export interface GetAccountRequest {
    lang?: GetAccountLangEnum;
}

export interface GetWeBenefitInfoRequest {
    lang?: GetWeBenefitInfoLangEnum;
}

/**
 * no description
 */
export class AccountApi extends BaseAPI {

    /**
     * Returns account data with an overview of services
     * GetAccount
     */
    getAccount({ lang }: GetAccountRequest): Observable<Account>
    getAccount({ lang }: GetAccountRequest, opts?: OperationOpts): Observable<RawAjaxResponse<Account>>
    getAccount({ lang }: GetAccountRequest, opts?: OperationOpts): Observable<Account | RawAjaxResponse<Account>> {

        const headers: HttpHeaders = {
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Bearer authentication
        };

        const query: HttpQuery = {};

        if (lang != null) { query['lang'] = lang; }

        return this.request<Account>({
            url: '/api/account',
            method: 'GET',
            headers,
            query,
        }, opts?.responseOpts);
    };

    /**
     * Returns account data with an overview of services
     * GetWeBenefitInfo
     */
    getWeBenefitInfo({ lang }: GetWeBenefitInfoRequest): Observable<Array<WeBenefitInfo>>
    getWeBenefitInfo({ lang }: GetWeBenefitInfoRequest, opts?: OperationOpts): Observable<RawAjaxResponse<Array<WeBenefitInfo>>>
    getWeBenefitInfo({ lang }: GetWeBenefitInfoRequest, opts?: OperationOpts): Observable<Array<WeBenefitInfo> | RawAjaxResponse<Array<WeBenefitInfo>>> {

        const headers: HttpHeaders = {
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Bearer authentication
        };

        const query: HttpQuery = {};

        if (lang != null) { query['lang'] = lang; }

        return this.request<Array<WeBenefitInfo>>({
            url: '/api/account/webenefits',
            method: 'GET',
            headers,
            query,
        }, opts?.responseOpts);
    };

}

/**
 * @export
 * @enum {string}
 */
export enum GetAccountLangEnum {
    EN = 'en',
    DE = 'de',
    FR = 'fr',
    IT = 'it'
}
/**
 * @export
 * @enum {string}
 */
export enum GetWeBenefitInfoLangEnum {
    EN = 'en',
    DE = 'de',
    FR = 'fr',
    IT = 'it'
}
