// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    CreateOfferRequest,
    CreateOfferResponse,
    CreateOfferWithPrintRequest,
    CreateOfferWithPrintResponse,
} from '../models';

export interface CreateOfferRequest {
    body: CreateOfferRequest;
}

export interface CreateOfferWithPrintRequest {
    body: CreateOfferWithPrintRequest;
}

/**
 * no description
 */
export class OfferApi extends BaseAPI {

    /**
     * Create Offer
     * CreateOffer
     */
    createOffer({ body }: CreateOfferRequest): Observable<CreateOfferResponse>
    createOffer({ body }: CreateOfferRequest, opts?: OperationOpts): Observable<RawAjaxResponse<CreateOfferResponse>>
    createOffer({ body }: CreateOfferRequest, opts?: OperationOpts): Observable<CreateOfferResponse | RawAjaxResponse<CreateOfferResponse>> {
        throwIfNullOrUndefined(body, 'body', 'createOffer');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Bearer authentication
        };

        return this.request<CreateOfferResponse>({
            url: '/api/offer',
            method: 'POST',
            headers,
            body: body,
        }, opts?.responseOpts);
    };

    /**
     * Create Offer with Print
     * CreateOfferWithPrint
     */
    createOfferWithPrint({ body }: CreateOfferWithPrintRequest): Observable<CreateOfferWithPrintResponse>
    createOfferWithPrint({ body }: CreateOfferWithPrintRequest, opts?: OperationOpts): Observable<RawAjaxResponse<CreateOfferWithPrintResponse>>
    createOfferWithPrint({ body }: CreateOfferWithPrintRequest, opts?: OperationOpts): Observable<CreateOfferWithPrintResponse | RawAjaxResponse<CreateOfferWithPrintResponse>> {
        throwIfNullOrUndefined(body, 'body', 'createOfferWithPrint');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Bearer authentication
        };

        return this.request<CreateOfferWithPrintResponse>({
            url: '/api/offerWithPrint',
            method: 'POST',
            headers,
            body: body,
        }, opts?.responseOpts);
    };

}
