// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    CompanyResponse,
} from '../models';

export interface GetCompanyByUIDRequest {
    uid: string;
}

/**
 * no description
 */
export class UIDApi extends BaseAPI {

    /**
     * Get Company By UID
     * GetCompanyByUID
     */
    getCompanyByUID({ uid }: GetCompanyByUIDRequest): Observable<CompanyResponse>
    getCompanyByUID({ uid }: GetCompanyByUIDRequest, opts?: OperationOpts): Observable<RawAjaxResponse<CompanyResponse>>
    getCompanyByUID({ uid }: GetCompanyByUIDRequest, opts?: OperationOpts): Observable<CompanyResponse | RawAjaxResponse<CompanyResponse>> {
        throwIfNullOrUndefined(uid, 'uid', 'getCompanyByUID');

        const headers: HttpHeaders = {
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Bearer authentication
        };

        return this.request<CompanyResponse>({
            url: '/api/company/{uid}'.replace('{uid}', encodeURI(uid)),
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

}
