// tslint:disable
/**
 * Commerce Service API
 * API for Digital Commerce Platform
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    ValidateServiceSettingRequest,
    ValidateServiceSettingResponse,
} from '../models';

export interface ValidateServiceSettingPinPukRequest {
    serial: string;
    validateServiceSettingRequest: ValidateServiceSettingRequest;
}

/**
 * no description
 */
export class UtilityApi extends BaseAPI {

    /**
     * Validate pin puk
     */
    validateServiceSettingPinPuk({ serial, validateServiceSettingRequest }: ValidateServiceSettingPinPukRequest): Observable<ValidateServiceSettingResponse>
    validateServiceSettingPinPuk({ serial, validateServiceSettingRequest }: ValidateServiceSettingPinPukRequest, opts?: OperationOpts): Observable<RawAjaxResponse<ValidateServiceSettingResponse>>
    validateServiceSettingPinPuk({ serial, validateServiceSettingRequest }: ValidateServiceSettingPinPukRequest, opts?: OperationOpts): Observable<ValidateServiceSettingResponse | RawAjaxResponse<ValidateServiceSettingResponse>> {
        throwIfNullOrUndefined(serial, 'serial', 'validateServiceSettingPinPuk');
        throwIfNullOrUndefined(validateServiceSettingRequest, 'validateServiceSettingRequest', 'validateServiceSettingPinPuk');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ValidateServiceSettingResponse>({
            url: '/api/mobile/validateServiceSetting/{serial}'.replace('{serial}', encodeURI(serial)),
            method: 'POST',
            headers,
            body: validateServiceSettingRequest,
        }, opts?.responseOpts);
    };

}
